### ISSUE TITLE
Send telemetry without recurring device registration call

### ISSUE THREAD

**Issue by BhupalPatil** [Azure/azure-iot-sdk-csharp#1043]
OS - Windows 10/Windows 7
.net Environment - .net 4.7.2 OR .net core 2.1
SDK - Microsoft.Azure.Devices.Client - 1.21.0
          Microsoft.Azure.Devices.Provisioning.Client - 1.4.0
          Microsoft.Azure.Devices.Provisioning.Transport.Mqtt - 1.1.8

Description of the issue:

I managed to register device (x509 certificate authentication) via DPS and able to send message and upload files.

What I'm trying to achieve is once device is registered successfully next time I want to verify device is already there so I want to skip RegisterAsync step and directly send the JSON message/upload files to IOT hub. any reference for this?

**Skip below step as it is already registered.**
Console.Write("ProvisioningClient RegisterAsync . . . ");
DeviceRegistrationResult result = await _provClient.RegisterAsync().ConfigureAwait(false);

**Do below with connecting to DPS and upload json message/file... (without calling registerasync method)**
await iotClient.SendEventAsync(new Message(Encoding.UTF8.GetBytes("test message"))).ConfigureAwait(false);

**Comment by bikamani** [comment]
@BhupalPatil Thank you for github issue. We will look into this and get back to you!

**Comment by CIPop** [comment]
@BhupalPatil after you've called the provisioning code once, using the X509 certificate, you can simply create a new DeviceClient using `DeviceAuthenticationWithX509Certificate(deviceId, myX509Certificate2);`, skipping the registration.

See https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/provisioning/Samples/device/Common/ProvisioningDeviceClientSample.cs#L47 for how the DeviceClient is created.
You can skip creating the `SecurityProviderX509` and directly pass in the `X509Certificate2` object. (See how the `X509Certificate2` is created from a file here: https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/provisioning/Samples/device/X509Sample/Program.cs#L59. We recommend storing the certificates in a certificate store instead of files and secure them using a service account instead of a hard-coded password.)

For this to work, your device needs to somehow "remember" that it provisioned. You are also loosing some of the Provisioning service features that allow it to change hubs, etc.

**Comment by az-iot-builder-01** [comment]
@BhupalPatil, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by BhupalPatil** [comment]
Thanks @CIPop , I will try these steps and see if I can achieve this. I'm just trying to explore the options and see if I can gain some performance by skipping device registration step.
