### ISSUE TITLE
How to retrieve TransportType from a ModuleClient instance

### ISSUE THREAD

**Issue by marcopiuma** [Azure/azure-iot-sdk-csharp#1045]
Is there a way to query the current TransportType used by ModuleClient instance?. I'm implementing a singleton wrapper around ModuleClient and in order to determine if a requested ModuleClient is conflicting with an existing instance I would like to compare the TransportType passed in the create* api with the one of the existing instance, but could not find a way to query it.
thanks

**Comment by CIPop** [comment]
@marcopiuma no, the client instances are immutable: since the application creates them, the current design doesn't expose information passed during creation. The reason is that this information may not be stored in a format that can be exposed later on as the original format (e.g. we do not store a connection string).
Since you are creating a wrapper, you should already have the ability to capture the parameters passed at creation and allow for querying later on.

**Comment by az-iot-builder-01** [comment]
@marcopiuma, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
