### ISSUE TITLE
C2D Feedback reciever throws Operation was canceled

### ISSUE THREAD

**Issue by fasigpt** [Azure/azure-iot-sdk-csharp#1052]
Old Issue: https://github.com/Azure/azure-iot-sdk-csharp/issues/156
 
We are sending C2D messages and then using a separate **webjob** to check that the messages had been received, based upon the suggestion in our documentation here:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d#receive-delivery-feedback

The operation fails when trying to fetch the DeviceFeedback messages from IOTHUB using the [var feedbackBatch = await feedbackReceiver.ReceiveAsync();] statement in webjobs after deploying the code in azure.  

Exception:
![image](https://user-images.githubusercontent.com/11519211/64668005-89d3c800-d479-11e9-8805-ddefc767d6d2.png)

at Microsoft.Azure.Devices.AmqpFeedbackReceiver.d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NextGenGw.WebJobs.Services.DeviceFeedback.FeedbackReceiver.d__5.MoveNext()

How do we fix this error which is happening when we run under webjob.

**Comment by PriyaDhiv** [comment]
@fasigpt, @az-iot-builder-01, please find few details regarding the issue, since the hostname and deviceId belongs to organization, I removed the hostname details. 

| Required information          | Examples                                        |
| ----------------------------- | ----------------------------------------------  |
| TimeFrame (include time zone) | 2019-08-28T07:19:19Z- 2019-08-28T07:24:19Z (UTC)|
| SDK that failed (include NuGet Version) | Devices|EventHubs|ServiceClient       |
| Configuration delta | Normal Azure function to receives the device ACK/NACK by listening IOTHUB. |
| OS version, SKU and CPU arch | Windows 10 Pro |
| .NET Target Framework Moniker | netcoreapp2.1 |
| Device Type | Radio communication-based Loader |
| Device Id | For all devices |
| Description of issue | Facing the same operation failure issue when trying to fetch the DeviceFeedback messages from IOTHUB using the [var feedbackBatch = await feedbackReceiver.ReceiveAsync();] statement in webjobs after deploying the code in azure |
| Repro code [if available] | var feedbackBatch = await feedbackReceiver.ReceiveAsync(); |
| Expected result | Need to record device feedback, but webjob was failed with exceptions. |
| Actual result | at Microsoft.Azure.Devices.AmqpFeedbackReceiver.d__15.MoveNext()--- End of stack trace from previous location where exception was thrown ---at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task  task)at NextGenGw.WebJobs.Services.DeviceFeedback.FeedbackReceiver.d__5.MoveNext() |

![image](https://user-images.githubusercontent.com/55128272/65236370-10ca1580-daf6-11e9-9a7e-52431639bc67.png)

**Comment by PriyaDhiv** [comment]
did anyone find any solution or any better idea regarding the publishing of Cloud to Device communication receiver of IoTHub functionality in a webpage.

**Comment by bikamani** [comment]
@fasigpt , @PriyaDhiv Thanks for your patience and providing information based on the template. Is this issue still noticed? 

If so, can you please describe your web job more in detail? Is Device Client calling CompleteAsync for each C2D message received? Can you please describe the scenario to help with repro?

Thanks.

**Comment by bikamani** [comment]
Closing as there has not been any update.
