### ISSUE TITLE
Add support for CancellationToken in async methods

### ISSUE THREAD

**Issue by twsouthwick** [Azure/azure-iot-sdk-csharp#114]
I recently started playing with the SDK for a project and noticed that none of the async methods accept a cancellation token. Is a different pattern used in this SDK than cancellation tokens? If not, can we add support for them?

**Comment by jasmineymlo** [comment]
You are correct that the current sdk accept cancellation token.  We do pass cancellation token internally with operation timeout, so that operations will be cancelled by the end of the set retry duration.  Feel free to share your use case and vote in this [link](https://feedback.azure.com/forums/321918-azure-iot/suggestions/15031800-receiveasync-method-on-deviceclient-to-take-in-a-c).

**Comment by twsouthwick** [comment]
I added a comment there. This is really necessary if you want to give people fine grained control over the lifetime of the tasks - otherwise you're stuck waiting for a timeout even though you may have (based on other logic) already decided to cancel the operation.

**Comment by tameraw** [comment]
@twsouthwick - Agree with you. We're adding this to our backlog to provide CancellationToken for all our Async APIs.

**Comment by az-iot-builder-01** [comment]
@twsouthwick, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
