### ISSUE TITLE
Follow up on #1122

### ISSUE THREAD

**Issue by hanabi1224** [Azure/azure-iot-sdk-csharp#1180]
@abhipsaMisra Thanks for the fix of issue https://github.com/Azure/azure-iot-sdk-csharp/issues/1122 you made yesterday.  I open this issue because the original one actually pointed out 2 issues there, however, I don't think the major issue gets fixed appropriately. 

The issue being fixed by https://github.com/Azure/azure-iot-sdk-csharp/pull/1175 is, switching from DateTime to DateTimeOffset to keep timezone info which is awesome, but it does not really fix the crash,  the real issue here is that, as a library, it should always explicitly set proper Json.Net settings instead using default because the default Json.Net setting can be easily overwritten thus causes unexpected errors in the library.   Take this case as an example,  by changing DateTime to DateTimeOffset, it can still crash if a user set default json.net setting with below code.  
```csharp
JsonConvert.DefaultSettings = () =>new JsonSerializerSettings
 {
        DateParseHandling = DateParseHandling.DateTime,
 };
```
The point is that, besides DateParseHandling, there're so many configs that can be overwritten by user, and it's only safe when the library explicitly set it.  Please let me know if that does not make sense, thanks!

**Comment by abhipsaMisra** [comment]
The service client currently does not set any explicit JSON serialization settings, but instead provides the application the option to customize the settings. I will look into if setting default settings for serialization is an option we want to use for our service client.

On the above note regarding the DateParseHandling settings, the DateTimeOffset structure still contains the DateTime object, and therefore should not throw any exception if the application sets the Json DateParseHandling property to DateTime.
If you still see an exception, please share the error stack trace, so that we can debug this issue further!

**Comment by az-iot-builder-01** [comment]
@hanabi1224, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by abhipsaMisra** [comment]
This was a good point @hanabi1224, thank you for bringing this to our attention. We decided to parse the date returned by the service, and return the DateTime value; instead of deserializing them. Your global serializer settings should no longer impact the Twin object.
