### ISSUE TITLE
Device Client RecieveAsync throws OperationTimeOut Exception

### ISSUE THREAD

**Issue by JiwanMS** [Azure/azure-iot-sdk-csharp#130]
The DeviceClient is throwing OperationTimeout exception with the latest Nuget version. We are creating a device scoped connection with IOT hub. We are creating a listener to IOT hub with TimeSpan.MaxValue as timeout but we are getting Operation Timeout exception after a few mins. We are observing this behavior after updating to latest nuget, with version 1.0.7  we are not seeing this issue.

**Comment by jasmineymlo** [comment]
The OperationTimeout exception is defaulted to 4 minutes and it is applied on all device client operations.  An operation will retry until operation timeout.  In this case, when ReceiveAsync(TimeSpan.MaxValue) is called, the default operation timeout will be reached before ReceiveAsync() operation complete if there is no C2D message within the time period.  The way to get around this might be to set OperationTimeout to a longer time so that it wouldn't expire before message arrival.  Setting OperationTimeout = 0 would mean infinite retries.  Bear in mind that the operation timeout applies to all operations.  Thanks.

**Comment by amoghnatu** [comment]
This is happening with the NuGet package version 1.5.0 as well.

**Comment by JiwanMS** [comment]
Hi Amog, We were able to get around this issue by setting the OperationTimeoutInMilliseconds of DeviceClient to 0. The exception after the specified timeout(30-40sec in your case) is expected as the operation has timed out. You can set the timeout value to TimeSpan.Max in case you want a larger timeout.

**Comment by amoghnatu** [comment]
Why should it throw an exception? Shouldn't it return null after the specified timeout if there is no message in the device queue? The documentation also mentions the same. That it would return null after the specified timeout if there is no message in the queue. https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d

Refer to the section just after the code sample of receive async. Or am I missing something?

**Comment by amoghnatu** [comment]
**Update**
I just realized, I was setting the same timeout value for DeviceClient's OperationTimeoutInMilliSeconds property and also the Timeout value of ReceiveAsync(Timeout) call. This was causing the receive call to always throw the Timeout exception. My bad! After correcting the timeouts, the code is working as expected.

**Comment by jasmineymlo** [comment]
Great to know.  Thanks.
