### ISSUE TITLE
Platform not supported exception on Windows 10 - dotnetcore, when listening on C2D messages with Amqp_WebSocket_Only

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-iot-sdk-csharp#140]
hello all,

i have a dotnetcore program that uses a DeviceClient with AmqpTransportSettings that have the Amqp_WebSocket_Only protocol.  I am shipping a product that uses the SDK and that should support websocket
When running this, I get the following exception on dotnetcore, on my Windows 10: **Operation is not supported on this platform**.  I pasted the stack trace below and it seems the issue is with the SystemWebProxy class.  

Operation is not supported on this platform.
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at Microsoft.Azure.Devices.Client.IotHubConnection.<CreateClientWebSocketAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.IotHubConnection.<CreateClientWebSocketTransportAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.IotHubConnection.<CreateSessionAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.IotHubSingleTokenConnection.<CreateSessionAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.FaultTolerantAmqpObject`1.<OnCreateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Singleton`1.<CreateValue>d__19.MoveNext()
```

**Comment by SamVanhoutte** [comment]
is there a work around for this, or do we have to wait for this to be fixed, become available in the SDK ?

**Comment by sergaz-msft** [comment]
Hello @SamVanhoutte please let me first reproduce this issue on my environment and I will check alternatives. Thanks for your patience.

**Comment by yfakariya** [comment]
@SamVanhoutte @sergaz-msft 

I also faced this issue.

This seems to be by design for .NET Core as code in [1.1](https://github.com/dotnet/corefx/blob/374c16c53bf195cb0985b018fda2e42a762c7b15/src/System.Net.Requests/src/System/Net/SystemWebProxy.cs#L61) and [2.0](https://github.com/dotnet/corefx/blob/1fd3f2c47ee9d194a9eef369f5ee265cf38de458/src/System.Net.Requests/src/System/Net/SystemWebProxy.cs#L47) say. 

In my previous (rejected) PR(#53), I resolved this issue by implementing environment variable based `IWebProxy` implementation instead of `DefaultWebProxy`
* [Custom IWebProxy](https://github.com/yfakariya/azure-iot-sdk-csharp/blob/316e0a7e6a60404dfd4808b7f3e396fe56745bac/device/Microsoft.Azure.Devices.Client.NetStandard/Transport/EnvironmentWebProxy.cs)
* [Usage in IotHubConnection.cs](https://github.com/yfakariya/azure-iot-sdk-csharp/blob/316e0a7e6a60404dfd4808b7f3e396fe56745bac/device/Microsoft.Azure.Devices.Client/IotHubConnection.cs#L320)

Although above custom `IWebProxy` implementation is naive especially for Windows, I hope this helps to analyze and solve this issue.

**Comment by SamVanhoutte** [comment]
Thanks @yfakariya, cc @sergaz-msft

So, as you PR got rejected, does this mean the IoT client SDK won't implement a fix for this?  To my understanding, the SystemWebProxy is designed so that users of that class (in this case the IoT Hub team), have to handle the PlatformNotSupported exception:

>         // This is a sentinel object and can't support the GetProxy or IsBypassed
        // methods directly. Our .NET Core and .NET Native code will handle this exception
        // and call into WinInet/WinHttp as appropriate to use the system proxy.

I really don't feel like starting my own implementation of IoT Hub SDK just because of this issue.

**Comment by yfakariya** [comment]
@SamVanhoutte 
I should do follow up for this.
Although it is still inconvenient, you can set `WebRequest.DefaultWebProxy` with your own `IWebProxy` implementation instead of whole IoT Hub Device client. You can refer my past implementation to implement custom `IWebProxy` implementation.

I agree the SDK should support zero configuration for web proxy settings in .net core.

**Comment by SamVanhoutte** [comment]
@yfakariya 
Thanks for your suggestion, should have figured that out as well.  
The thing is: I am not using a proxy in this case.  I just need the default web proxy.  So, I tried setting `WebRequest.DefaultWebProxy = null; `, but that resulted in an exception with the following message: `A certificate is required to complete client authentication. ` 
I don't see where that exception is coming from.

**Comment by sergaz-msft** [comment]
Hello @SamVanhoutte  and @yfakariya .
I have made the changes in the code in order to enable C2D messages with Amqp_WebSocket_Only. We need to do some tests before releasing them.

Thank you for your patience.

**Comment by SamVanhoutte** [comment]
Hello @sergaz-msft ,
Has this been pushed to a public branch already?  Happy to include it and do some testing myself
Best regards

**Comment by sergaz-msft** [comment]
Hi @SamVanhoutte and @yfakariya , The changes have been commited and will come out on the next release 9/22. Please feel free to test the changes right away and let me know the results.

All Best!
