### ISSUE TITLE
Calling SetDesiredPropertyUpdateCallbackAsync causes 10 reconnects

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#1481]
In order to ensure a DeviceClient gets all desired property updates after the connection is established, the callback should logically be registered before OpenAsync is called. However, in this minimal repro, calling SetDesiredPropertyUpdateCallbackAsync  before or after results in repeated reconnects as evidenced by the output of the connection status change event handler. For example:

```
	class Program
	{
		static ManualResetEventSlim manualReset = new ManualResetEventSlim(false);
		static async Task Main(string[] args)
		{
			var deviceConnectionString = "<your connection string>"; 
			var deviceClient                   = DeviceClient.CreateFromConnectionString(deviceConnectionString);

			deviceClient.SetConnectionStatusChangesHandler(OnConnectionStatusChange);
			await deviceClient.SetDesiredPropertyUpdateCallbackAsync(OnDesiredPropertyUpdate, deviceClient);
			await deviceClient.OpenAsync();
			await Task.Delay(5000);

			manualReset.Wait();
		}

		private static Task OnDesiredPropertyUpdate(TwinCollection desiredProperties, object userContext)
		{
			manualReset.Set();
			return Task.CompletedTask;
		}

		private static void OnConnectionStatusChange(ConnectionStatus status, ConnectionStatusChangeReason reason) =>
			Console.WriteLine($"Connection status: {status} Reason: {reason}");
	}
```

### Output:

Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok
Connection status: Disconnected_Retrying Reason: Communication_Error
Connection status: Connected Reason: Connection_Ok

### Configuration:
Microsoft Windows [Version 10.0.19041.388]
Microsoft.Azure.Devices.Client 1.27.0
.Net framework 4.6.1 console application

**Comment by v-tbert** [comment]
I realized that I had left a connection open for the same device on another machine. Ideally this would return a more specific error message when a duplicate connection is made but that is a feature request, not a bug.

**Comment by az-iot-builder-01** [comment]
@v-tbert, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by xela-95** [comment]
Hi @v-tbert i'm having the exact same issue!
I didn't have understood if it is possible for two modules on the same device to have a device client connection open and hence receiving desired properties updates. Because this may be the source of the problem.

**Comment by abhipsaMisra** [comment]
To add some additional context to the original issue opened:
- opening multiple connections against the same device/ module instance will cause them to both fight for the same resources, and this will show up as the series of connections and disconnections that you've reported above. This is because:
  instance1 will connect to service -> report "connected" status -> instance2 will connect to service -> service will see this as a duplicate connection and will disconnect instance1 -> instance2 will report "connected" status -> instance1 will report "disconnected_retrying" status -> the sdk will try to recover the instance1 connection -> instance1 will connect to service -> service will see this as a duplicate connection and will disconnect instance2 -> so on.
  I agree that it would be helpful to propagate back to the caller that the reason that they're seeing this behavior is because of duplicate connections being opened against the same device/ module identity. For now, this behavior propagates up to the client as a connection disconnect, however, if you collect sdk logs, you would be able to see some more details logged.
- All of the client operations have implicit opne implemented. What this means is that, if you call `SetDesiredPropertyUpdateCallbackAsync` on a newly initialized client, it will first check if it has a connection open, and if not, it will open one. For this reason, you do not need to follow it with a call to `OpenAsync`.

@xela-95 Do you need any help from us on this issue, or were you able to unblock yourself?

**Comment by xela-95** [comment]
@abhipsaMisra Thank you for you answer.
Regarding the first point, this makes sense to me in explaining the strange behavior of continuous connections and disconnections. For this reason I will try to implement the configuration for my modules in a module twin, such that each module has a separate connection with the module client instead of competing for the device client.

It was not so clear to me the second point: in my module initialization I'm executing the following  code:
```
deviceClient = DeviceClient.Create(iotHubHostname,
              new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, deviceKey), transportType);
await deviceClient.OpenAsync();

await deviceClient.SetDesiredPropertyUpdateCallbackAsync(OnDesiredPropertiesUpdate, null);
```
What you're saying is that it is an error to call the OpenAsync and then SetDesiredPropertyUpdateCallbackAsync?

**Comment by abhipsaMisra** [comment]
@xela-95 It is not an _error_ to call `OpenAsync` and then `SetDesiredPropertyUpdateCallbackAsync`, neither is it an error to do it the other way around - call `SetDesiredPropertyUpdateCallbackAsync` first and then `OpenAsync`.
What I meant is, if your application code initializes a client instance and then immediately needs to subscribe to desired property updates, then you can do so by calling `SetDesiredPropertyUpdateCallbackAsync` directly. You do not need to prefix or suffix this call with a call to `OpenAsync`. A call to `SetDesiredPropertyUpdateCallbackAsync` will automatically open up a connection, if one isn't already open.

Calling `OpenAsync` explicitly makes sense when all you want to do is open up a connection to IoT Hub and possibly keep monitoring the client's connection status via the connection status change callback. If your goal is to perform an operation, then you can leave out the explicit `OpenAsync` call and instead rely on the implicit open that all client operations have inbuilt support for.

**Comment by abhipsaMisra** [comment]
Also, I'll keep an eye out on this issue for any updates from you, but generally we don't monitor closed issues. Feel free to open a new GitHub issue if you face any additional issues!

**Comment by xela-95** [comment]
@abhipsaMisra Ok now it's more clear. 
Then is it correct to say that if one of my custom modules needs to be updated only for desired property changes, I will only call ```SetDesiredPropertyUpdateCallbackAsync ``` without an explicit call on ```OpenAsync```. 
Will this prevent my modules in conflicting for the connection to the same device?

**Comment by abhipsaMisra** [comment]
@xela-95 Yes, if all your custom module needs is monitoring for desired property update notifications, then you can initialize a new module client instance and then set `SetDesiredPropertyUpdateCallbackAsync`. You should also set the connection status change callback and use that for monitoring your client's connection state and ensuring that you take appropriate action if the client becomes disconnected. Note that for transient faults the sdk would try to recover the connection internally and would return a status of "disconnected_retrying". When the client is at this state, you do not need to take an action. You will need to take an action only when the sdk isn't retying internally and returns a status of "disconnected".
See [this](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/DeviceReconnectionSample) sample for more details on how to handle client reconnection.

All of your modules have different identities, which in turn differ from the identity of your parent device. As long as you initialize each of the module and device clients by their own identity you will not see an conflict for the connection.
Eg. A module connection string is of the format: `HostName=<iot-hub-hostname>;DeviceId=<device-id>;ModuleId=<module-id>;SharedAccessKey=<shared-access-key>`
A device connection string if of the format: `HostName=<iot-hub-hostname>;DeviceId=<device-id>;SharedAccessKey=<shared-access-key>`
