### ISSUE TITLE
Why is SecurityProviderTpmHsm.cs trying to create the TPM EK?

### ISSUE THREAD

**Issue by rgl** [Azure/azure-iot-sdk-csharp#1557]
Why is SecurityProviderTpmHsm.cs trying to create the TPM EK at the following line?

https://github.com/Azure/azure-iot-sdk-csharp/blob/32166465d4d5d9d4d6dd9a35ad85bd19c38958c0/security/tpm/src/SecurityProviderTpmHsm.cs#L280-L293

Isn't it an error if the EK is not present on the TPM? Does the TPM even allow us to create the EK?

**Comment by timtay-microsoft** [comment]
We'll try to take a look at this soon. Is this a blocking issue for you, or more of a question?

**Comment by rgl** [comment]
Its not blocking me; its more of a question.

**Comment by timtay-microsoft** [comment]
Sorry for the delay on this one. While the most typical case is that a device get's its endorsement key installed at manufacturing time and never cleared, it is possible that a given TPM will be asked to clear it's existing keys and to install new keys.

As for what our security provider in particular is doing, it is setup to read the endorsement key and use it, provided that they TPM has one. Otherwise, it just creates an endorsement key for you, and uses that new key.

**Comment by timtay-microsoft** [comment]
Closing this issue since the question has been answered. Feel free to open another issue if you have any additional questions.

**Comment by rgl** [comment]
Understood! Thank you!
