### ISSUE TITLE
File upload over main communication channel

### ISSUE THREAD

**Issue by Perun85** [Azure/azure-iot-sdk-csharp#1567]
We are using CA signed certificates for authentication. Their chain has following hierarchy:
CA ->
Intermediate CA ->
Customer CA (we have around 1000 customers and their number is growing) ->
Device certificate

Due to IoTHub's inability to support more then 20 certificates we cannot register entire chain.
Even without entire chain AMQP and MQTT endpoints of IoTHub are available to us, but we cannot use HTTPS.

In latest versions of SDK there is new API for uploading files to blob storage that is based on distribution of SAS tokens.
Communication between DeviceClient instance and IoTHub is done over HTTPS endpoint that we cannot use.

Is it possible to distribute SAS token over default communication channel?

**Comment by abhipsaMisra** [comment]
The endpoint that the device client interacts with to get the SAS token for file upload is available only over HTTP: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#initialize-a-file-upload

This is a contract set by the service, so unfortunately, the client cannot do anything about this here.
Please open a support request [here](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request), so that the service team can analyze the issue and provide you a recommendation.

**Comment by abhipsaMisra** [comment]
Please let me know if you have any further question, else I'll close this issue in 3 days. Thanks!

**Comment by az-iot-builder-01** [comment]
@Perun85, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
