### ISSUE TITLE
Azure iot hub sdk using deprecated WindowsAzure.Storage

### ISSUE THREAD

**Issue by ChangeTheCode** [Azure/azure-iot-sdk-csharp#1600]
I found out the azure iot hub sdk is using a deprecated nuget package (WindowsAzure.Storage). There it is recommend to move to the new packages which are: [Doc](https://www.nuget.org/packages/WindowsAzure.Storage/)
- Azure.Storage.Blobs
- Azure.Storage.Queues
- Azure.Storage.Blobs.Batch
- Azure.Storage.Files.Shares

What is the difference between the Microsoft.Azure.Storage and WindowsAzure.Storage Nuget packages? https://stackoverflow.com/a/53218759

**Comment by abhipsaMisra** [comment]
Thanks for raising this issue. As discussed [here](https://github.com/Azure/azure-iot-sdk-csharp/issues/1391#issuecomment-643433816), we aren't able to update the storage SDK dependency, since  Azure.Storage.* packages do not support .NET451 (which is one our the supported targets for our client library).
To get around requiring users to use a deprecated storage library to perform upload operations, we have split the Upload API into three separate APIs, allowing for more-granular control.
From [here](https://github.com/Azure/azure-iot-sdk-csharp/issues/1391#issuecomment-644858137):

What this means is, instead of having a single API for file upload, doing the following:

1. Retrieve the sas URI from IoT Hub
2. Upload the file stream using storage SDK
3. Update the file upload status to IoT hub

we have now broken these to 3 separate steps. The Microsoft.Azure.Devices.Client SDK has new APIs for step 1 and step 3, while for step 2 the user is free to use any version of the Storage SDK to perform the actual upload operation.
This means that your application doesn't need to depend on the deprecated Storage SDK version to perform the file upload.

**Comment by abhipsaMisra** [comment]
Closing this issue with the above mitigation steps.
Feel free to re-open this issue if you have further questions/ comments.

**Comment by az-iot-builder-01** [comment]
@ChangeTheCode, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
