### ISSUE TITLE
MQTT connection pooling

### ISSUE THREAD

**Issue by kamilzzz** [Azure/azure-iot-sdk-csharp#1649]
Does MQTT transport type supports connection pooling?

I've tried to simulate several devices sending message using sdk and I've noticed that for 1k devices it opened more than 1k connections.

**Comment by abhipsaMisra** [comment]
No, MQTT does not in fact support connection pooling. With every device client instance instantiated, it will open up a new connection. This is a protocol level restriction, since each MQTT connection requires its own CONNECT packet.
If you require connection pooling, we recommend you use either AMQP (sdk level support available), or HTTPS (.NET native support available).

Let  us know if you have any further questions.

**Comment by az-iot-builder-01** [comment]
@kamilzzz, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
