### ISSUE TITLE
Add capability to define custom metadata for uploaded files

### ISSUE THREAD

**Issue by mpalumbo7** [Azure/azure-iot-sdk-csharp#165]
It would be convenient to allow the device side to send custom metadata about uploaded files by:

1. Setting metadata on the storage account blob ([Suggestion on Azure Feedback](https://feedback.azure.com/forums/321918-azure-iot/suggestions/20386327-allow-to-attach-metadata-to-blob-when-uploading-fi))
1. Appending custom fields to the [file upload notification](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#notify-iot-hub-of-a-completed-file-upload)

In either case, the [DeviceClient.UploadToBlobAsync()](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/DeviceClient.cs#L875) method which calls the  [HttpTransportHandler.UploadToBlobAsync()](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/Transport/HttpTransportHandler.cs#L210) method could be updated to have an optional key-value pair argument that contains the metadata.

For the first case, the metadata can be added to the blob via the [user defined metadata](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-properties-metadata), without affecting other systems.

For the second case, the REST API may have to be updated. The file upload request body currently only defines [blobName](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#initialize-a-file-upload). Alternatively, the custom metadata could be part of the [file upload notification](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#notify-iot-hub-of-a-completed-file-upload) body.

Thoughts? I'd be willing to issue a pull request if someone can guide me on the quality expectations.

**Comment by CIPop** [comment]
Thanks @ewok2030 for the idea and offer to help with the implementation!
Please provide the new API proposal documentation (see a good example/template here: https://github.com/dotnet/corefx/issues/271). If you don't already have the code, you could defer the PR until we agree on the API shape.

Regarding quality, you will need to provide both [UnitTests](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/device/tests) and [E2E functional tests.](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/e2e/Microsoft.Azure.Devices.E2ETests/FileUploadE2ETests.cs) 

We're still working out the details on prerequisites and documentation for the E2E tests but you can read [the InitializeEnvironment method](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/e2e/Microsoft.Azure.Devices.E2ETests/TestUtil.cs#L60) to understand how to set up your service-side Azure environment as well as the client-side environment variables required for this test. You'll need to run at least the FileUploadE2ETests.cs prior us reviewing the PR. Since setup is complicated we can help running the rest of the E2E tests to ensure no regressions are introduced.

**Comment by tameraw** [comment]
@ewok2030 - Are you still planning to work on this? Thanks.

**Comment by ewok2030** [comment]
@tameraw - I was planning on it, but now I’m going to be busy for the next few weeks.

**Comment by RubiaL** [comment]
Thanks for the feedback. This is currently not a priority in our backlog and do not plan on adding this feature to our SDK. But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure portal](https://azure.microsoft.com/en-au/features/azure-portal/)

**Comment by az-iot-builder-01** [comment]
@CIPop, @mpalumbo7, @RubiaL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by sanjeev-magoo** [comment]
@RubiaL - Can you please let us know when you are picking up this functionality (define custom medata data for uplaoded files). We wanted to use this feature.

**Comment by sachazyto** [comment]
For example, if we have a robot using Azure IoT hub upload one (or several) map files, it would be great to have the possibility to upload attributes for that upload, for example, when it was generated, which type of sensors were used, which building the map represents etc... I know we could just put all those properties into a separate JSON file, and upload that file as well, but it feels like a workaround, and it's not trivial to determine which data was associated with a given upload (can't use the file name in a case there are multiple files being uploaded). When using a traditional HTTP multipart form post to upload files, we're able to pass metadata parameters along with the uploaded file(s), so it would be good for the Azure framework to have a similar degree of flexibility as what developers are used to when using HTTP. Note that this isn't C# specific (I'm personally using the python SDK), but I'm posting the comment here since the issue has already being raised here.
