### ISSUE TITLE
[Technical Question] MQTT_WSONLY System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by ulaurent** [Azure/azure-iot-sdk-csharp#1681]
I have a system that is trying to connect to the Hub that is throwing back this exception.

I have set the transport type to to MQTTWS_ONLY which communicates on port 443. I know MQTT communicates on port 8883. I am wondering what would possibly cause the error, as it also appears the IP address is shows port 8883 and not 443.

**MQTT transport exception ---> DotNetty.Transport.Channels.ConnectException: LogError connecting to 23.98.222.46:8883 ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond**

Any suggestions would be greatly appreciated. thanks!

**Comment by timtay-microsoft** [comment]
For reference, here is the log that is probably in question: https://github.com/Azure/azure-iot-sdk-csharp/blob/d7b3c6855b4fb6fe39c5e5fe57de9ab771883ac8/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L1248

The first thing that jumps out at me here is that the SDK loops over some set of IP Addresses and tries to connect until one succeeds. @azabbasi I'd start your debugging around there to see why the SDK does this.

Foreach loop link:
https://github.com/Azure/azure-iot-sdk-csharp/blob/d7b3c6855b4fb6fe39c5e5fe57de9ab771883ac8/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L1214

**Comment by azabbasi** [comment]
Thank you Tim, 
@ulaurent  if you can share the SDK logs at the time of this event with us, we might be able to better assist you
You can find the instructions to produce the SDK logs [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs)

**Comment by ulaurent** [comment]
@azabbasi Thank you! I found that port 8883 was blocked. Changing the provisioning registration handler to HTTP was a fix to communicate over port 443

https://github.com/Azure/azure-iot-sdk-csharp/blob/master/provisioning/transport/http/src/ProvisioningTransportHandlerHttp.cs

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @azabbasi, @ulaurent, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by azabbasi** [comment]
@ulaurent we are glad your issue is resolved, there is a bit of confusion regarding your scenario to us, can you elaborate what your scenario is ?
I am asking so we are better equipped in the future handling issues like this. 
My understanding was that your client was supposed to use 443 since it was a MQTT_WEBSOCKET_ONLY protocol, but you were noticing the IP address it was trying to access was on 8883. What I don't follow is how 8883 being unblocked was causing the issues if you were supposed to be using 443. 
We would  appreciate if you would share your scenario with us in more depth and let us know how your findings fixed the problem.
