### ISSUE TITLE
[feature request] Make DeviceClient extensible

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-iot-sdk-csharp#1791]
**Is your feature request related to a problem? Please describe.**
Make DeviceClient extensible so that we can build upon it, mock it, etc.

**Describe the solution you'd like**
I'm happy to open a PR to remove the `sealed` keyword on the class so that we can extend it.

**Describe alternatives you've considered**
N/A

**Additional context**
Relates to https://github.com/Azure/azure-iot-sdk-csharp/issues/61 & https://github.com/Azure/azure-iot-sdk-csharp/issues/110 which blocks us from writing tests as well.

Thank you for helping make this project even better!

**Comment by tomkerkhove** [comment]
> Regardless of the language, the described problem is a code smell in your application's design. See chapter 8 of Growing Object-Oriented Software, Guided by Tests for reasons to "Only Mock Types That You Own".

While I get the thought process behind this, if you depend on something as part of your business logic you still want to ensure that it gets called correctly. Today, there is no such way other than having an Azure IoT Hub instance around with pre-configured devices; then we are no longer talking about unit testing.

**Comment by fgheysels** [comment]
Maybe having an `IDeviceClient` and `IModuleClient` interface would be enough.  The existing DeviceClient and ModuleClient classes can implement it.   People who have those as a dependency can use frameworks like `Moq` to easily provide a mocked implementation of those interfaces, so that they can test their classes that have a dependency on DeviceClient/ModuleClient.

**Comment by tomkerkhove** [comment]
That would be fine for me as well

**Comment by vinagesh** [comment]
Adding an interface is not going to be feasible in this case. However, we do think that removing the sealed from the clients is an acceptable solutions. We will accept your pending PR request. 

If this is acceptable, can we close this issue?

**Comment by tomkerkhove** [comment]
It is for me, I think. Thank you!

Just out of curiosity, why is an interface not possible?

**Comment by vinagesh** [comment]
Adding an interface means, whenever we add something new, it will break everyone who is implementing the interface. We always try to ship code that is not a breaking change for consumers.

**Comment by tomkerkhove** [comment]
I think that would be fair but I also see your point.

**Comment by drwill-ms** [comment]
Specifically our factory methods to create a client would need to change type. We have strict guidelines not to change behavior in the client in ways that would break customers, because every tends to get cranky when their application doesn't build or crashes in new and exciting ways after updating to a new SDK.

FWIW, the SDK is not designed or a built a way we very much like. In many ways we are stuck with decisions from the past. However, we'll be looking at a big client redesign to start fresh to solve a lot of these problems (like unit testable clients, more control over the pipeline, diagnostics, etc.). The Azure SDK team started this effort across all of Azure a few moons ago, and we're getting more and more of our SDKs on board. If you are curious, you can read about the guidelines here: <https://azure.github.io/azure-sdk/dotnet_introduction.html>.

Thanks for finding a way to make our current client better. We appreciate it. :)

**Comment by tomkerkhove** [comment]
Thanks for sharing and I'm happy to help!

**Comment by vinagesh** [comment]
@tomkerkhove - I will be abandoning your PR. Here is the PR which has no build errors - https://github.com/Azure/azure-iot-sdk-csharp/pulls
Once that gets checked in and we have released a new version of the SDK, I will let you know.

**Comment by tomkerkhove** [comment]
Ok for me!

**Comment by tomkerkhove** [comment]
Just following up - Is there an ETA for a new version?

**Comment by vinagesh** [comment]
We just released the new version with these changes - https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-03-18

**Comment by ElD4n1** [comment]
Hello, thanks for working on this issue, but how is this supposed to be testable now when the only constructor of `ServiceClient` is still internal?

**Comment by vinagesh** [comment]
We have made mocking very easy in all the Service Clients if you want to check it out - We have released a version of our clients that is mockable now - https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2021-6-8

**Comment by tomkerkhove** [comment]
Awesome, thanks a lot!

**Comment by bqstony** [comment]
@drwill-ms i have also the problem to mock the `ModuleClient` class when i testing modulue to module communication. There is the same behavior like in the `DeviceClient`, the constructurs are internal.

I am using the 1.39.0 version.

Thank you.
