### ISSUE TITLE
Customizing blob path when uploading file from device to blob in IoT Hub

### ISSUE THREAD

**Issue by kunalwattamwar** [Azure/azure-iot-sdk-csharp#1794]
Problem: Device is uploading files to blob using IoT hub "File Upload" feature. API used: DeviceClient.UploadToBlobAsync()

On BLOB, **By default <Deviceid> folder is getting created & in that folder, files are getting uploaded.**
i.e. Device_id\test.xml

**Is it possible to customize default behaviour of <Deviceid> folder being created?**

i.e. I want below hierarchy when uploading file.
 Model_Name\Device_id>\test.xml

**Comment by abhipsaMisra** [comment]
Instead of using "DeviceClient.UploadToBlobAsync()", which uses a particular version of the storage sdk to perform the file upload operation; we recommend users user the granulated file upload APIs instead:
- GetFileUploadSasUriAsync() - to retrieve the file upload SAS Uri from IoT Hub
- Use any supported storage sdk to perform the file upload operation.
- CompleteFileUploadAsync() - to notify IoT Hub about completion of the upload operation.

Since you can use any supported storage sdk to perform the file upload, we recommend you review the options available here: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage#azure-storage-libraries-for-net, or reach out to the storage team for customizing the storage behavior.

**Comment by abhipsaMisra** [comment]
@kunalwattamwar While the above recommendation of using the granular APIs to perform file upload is still valid, it looks like the upload location is currently dictated by IoT Hub (and cannot be customized even if you used a different storage sdk). It looks like the blob for which the SAS Uri is returned is always in the format "<device_Id>/<file_name>": https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#initialize-a-file-upload

I'll reach out to the service team to see if this can be configured, but my above recommendation of simply using a different storage sdk is not going to solve this issue (since the sas uri returned by IoT Hub authenticates you to perform this upload against a specific endpoint, using this sas token to upload to a different blob location will fail, as expected).

**Comment by abhipsaMisra** [comment]
I synced up with the service team and it looks like the folder structure beginning with the device Id is mandated by IoT Hub. You are, however, free to specify any sub-folder hierarchy that you wish:
eg:
```json
{
    "blobName": "folder1/thisIsMyFile.txt"
}
```
will upload your file to "myIoTHubDevice/folder1/thisIsMyFile.txt".

Let me know if you have any further questions on this.

**Comment by kunalwattamwar** [comment]
@abhipsaMisra Appreciate your quick help and recommendations.
No further questions. 
Thanks.
