### ISSUE TITLE
DateTime json fields may lose data when retrieved

### ISSUE THREAD

**Issue by gmileka** [Azure/azure-iot-sdk-csharp#180]
We define the following property in the device twin:
"singleRebootTime": "2016-10-10T17:00:00Z"

When we traverse the returned JObject from the Azure SDK, we reach the parent node and do:
            JToken jValue;
            if (jObj.TryGetValue(propertyName, out jValue))
The problem is that jValue loses the UTC notion in the time (the 'Z'). So, at that point, we cannot know if the time passed in was local time or UTC.

It seems that the Json deserializer instance used by the SDK is using the default DateTime parsing - which causes the above behavior.

The information is in the tree. It just gets lost when conversion happens when we get the jValue.

For us to work around this, we can do something like:
            string jObjString = jObj.ToString();
            JsonSerializerSettings settings = new JsonSerializerSettings();
            settings.DateParseHandling = DateParseHandling.None;
            JObject reparsedObj = (JObject)JsonConvert.DeserializeObject(jObjString, settings);
            JToken jValue;
            if (reparsedObj.TryGetValue(propertyName, out jValue))

I think it makes sense that the SDK instance should disable DateTime parsing so client don't have to do this steps.

**Comment by ryan-z-johnson** [comment]
@gmileka  Sorry about the long wait. Do you have a code sample I could look at to make sure I mimic your setup in my testing. What version of the SDK are you using? Again this is just to mimic my development environment to be as much like yours.

**Comment by tameraw** [comment]
@gmileka - Would you be able to provide a PR for this? Thanks.

**Comment by ryan-z-johnson** [comment]
@gmileka - Would you be able to provide us a Pull Request for this. Thank you.

**Comment by zolvarga** [comment]
@gmileka 

Sorry for the long delay. 
I took a look at the issue and it looks like it has been fixed by a NewtonSoft library update. 
The server always sends the correct UTC time back regardless of the reported format and the SDK Twin implementation parses it correctly. 
Also you don't need to parse the object, use the Twin object for it. See the code below:

var propName = "singleRebootTime";
TwinCollection twc = new TwinCollection
{
    [propName] = "2016-10-10T17:00:00Z"
};

await client.UpdateReportedPropertiesAsync(twc);

Twin tw = await client.GetTwinAsync();

if (tw.Properties.Reported.Contains(propName))
{
    var propValue = tw.Properties.Reported[propName].Value;
    Console.WriteLine("PropertyValue: " + propValue);
}

I am closing this issue now, please reopen this or create a new one if you still have issue.

Best Regards,
Zoltan
