### ISSUE TITLE
[Bug Report] DeviceClient.Create causes exception after update to v1.34 or later

### ISSUE THREAD

**Issue by Alexbits** [Azure/azure-iot-sdk-csharp#1832]
After update to v1.34 or later, the DeviceClient.Create method fails. I had to downgrade to v1.33.1 to fix it.

Code:

```c#
 var client = DeviceClient.Create(_globalSettings.IotHubUri,
                                             new DeviceAuthenticationWithRegistrySymmetricKey(
                                                                     deviceInfo.Id,
                                                                     deviceInfo.IotHubKey),
                                                                     TransportType.Http1);
```

Exception:

System.NotImplementedException: The method or operation is not implemented.\n  at System.Globalization.CompareInfo.IndexOfCore (System.String source, System.String target, System.Int32 startIndex, System.Int32 count, System.Globalization.CompareOptions options, System.Int32* matchLengthPtr) [0x00006] in <0259240c66b143c79f181dc836ac854f>:0 \n  at System.Globalization.CompareInfo.IndexOf (System.String source, System.String value, System.Int32 startIndex, System.Int32 count, System.Globalization.CompareOptions options, System.Int32* matchLengthPtr) [0x00071] in <0259240c66b143c79f181dc836ac854f>:0 \n  at System.String.ReplaceCore (System.String oldValue, System.String newValue, System.Globalization.CultureInfo culture, System.Globalization.CompareOptions options) [0x0005d] in <0259240c66b143c79f181dc836ac854f>:0 \n  at System.String.Replace (System.String oldValue, System.String newValue, System.StringComparison comparisonType) [0x00055] in <0259240c66b143c79f181dc836ac854f>:0 \n  at Microsoft.Azure.Devices.Client.StringValidationHelper.IsBase64String (System.String value) [0x00000] in <68e0defabce4485280874d7a943d267c>:0 \n  at Microsoft.Azure.Devices.Client.DeviceAuthenticationWithRegistrySymmetricKey.SetKeyFromBase64String (System.String key) [0x00013] in <68e0defabce4485280874d7a943d267c>:0 \n  at Microsoft.Azure.Devices.Client.DeviceAuthenticationWithRegistrySymmetricKey..ctor (System.String deviceId, System.String key)

Xamarin
Android Device Emulator (Android Q - API 29)

**Comment by vinagesh** [comment]
Thanks for reporting. We don't officially support xamarin but will try to fix this issue that you are facing with our recent changes. In the meantime, does this unblock you?

Add the following constant to your .csproj:

`
 <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineConstants>NETSTANDARD2_0</DefineConstants>
  </PropertyGroup>
`

**Comment by Alexbits** [comment]
> Thanks for reporting. We don't officially support xamarin but will try to fix this issue that you are facing with our recent changes. In the meantime, does this unblock you?
> 
> Add the following constant to your .csproj:
> 
> `<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' "> <DefineConstants>TRACE;NETSTANDARD2_0</DefineConstants> </PropertyGroup>`

**Comment by Alexbits** [comment]
Hi, thank you for your reply! This does not solve the issue and I'm not sure how exactly it can. The code with DeviceClient.Create is in the NET Standard 2.1 class library which is shared between Android and iOS projects. What .csproj exactly you mean in this case?

**Comment by vinagesh** [comment]
The reason I thought it would solve your issue is that we added some conditional code based on netstandards in the SDK (compiler directives). This would only be a problem if you did not have a class library and directly installed the SDK on the xamarin android project as the xamarin android project does not have any netstandard target framework for the compiler directives to choose the correct path. 

But thanks for giving more details. I should be able to analyze it more today.

**Comment by vinagesh** [comment]
Which version of xamarin android are you using? https://github.com/dotnet/standard/blob/master/docs/versions.md

I'm wondering if the xamarin android you are using does not support .netstandard 2.1. Another thing to try would be to use .netstandard 2.0 in your library.

**Comment by Alexbits** [comment]
I use Android 11 as my target framework. It works fine with version 1.33 of Microsoft.Azure.Devices.Client. The NET Standard 2.1 can use a 2.0 class library, there is no issue with this.

**Comment by vinagesh** [comment]
It works fine with 1.33 because we are not using a functionality only supported in netstandard 2.1. If you target .netstandard 2.1 for your class library, what happens is that it expects the android runtime to have that implementation and it looks like that is missing. However, if you target .netstandard 2.0, the correct functionality will be picked up from the SDK. 

I was curious so I tried this out and found that if my class library targets .netstandard 2.1, I get the same System.NotImplementedException. However, when I target .netstandard 2.0, everything works fine in my android app. 

This is what I found about xamarin and .netstandard 2.1 - https://github.com/xamarin/xamarin-macios/issues/9255

So can you make this change in your library .csproj and test?
`<TargetFramework>netstandard2.1</TargetFramework> to <TargetFramework>netstandard2.0</TargetFramework>`

**Comment by vinagesh** [comment]
Just add some more explanation:
Here is the code snippet that decides which API to use for string replace. The one with InvariantCultureIgnoreCase is only supported on .netstandard 2.1 but it needs to be implemented (which is missing in xamarin android). However, if you target .netstandard 2.0, we will be using the other version of the string replace in the SDK, making your app work correctly. This is more a gap in the implementation of the library in xamarin. There is no issue with this on windows platform.
https://docs.microsoft.com/en-us/dotnet/api/system.string.replace?view=net-5.0#System_String_Replace_System_String_System_String_System_Boolean_System_Globalization_CultureInfo_
`
#if NETSTANDARD2_0 || NET451 || NET472
            value = value.Replace("\r", string.Empty)
                .Replace("\n", string.Empty);
#else
            value = value.Replace("\r", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("\n", string.Empty, StringComparison.InvariantCultureIgnoreCase);
#endif
`

**Comment by Alexbits** [comment]
Thank you for the detailed explanation. This is upsetting. I will check this out thoroughly. Unfortunately, I can't use 2.0 since I have multiple 2.1 dependencies where C# 8 is in use and switching to 2.0 is not an option at the moment.

**Comment by vinagesh** [comment]
I'm really sorry about this. I will try to find out more and if there is anything we can do from the SDK side to help. I don't have much idea about the xamarin support for .netstandard 2.1 itself.

**Comment by vinagesh** [comment]
It would also be good for you to open a github issue on xamarin to get the current information about their support.

**Comment by Alexbits** [comment]
Thank you @vinagesh I'll investigate this.

**Comment by vinagesh** [comment]
@Alexbits - I did try to contact some internal teams to find out more about Xamarin. Apparently they don't implement all of the .netstandard2.1 APIs. We are working on either getting this API added or finding a workaround in the SDK to unblock mobile customers. Even though we do not officially support mobile at the moment, it is in our charter and will be working on it soon. I know it is very inconvenient for you to change targets but that is definitely a workaround other than using the older version of our SDK. Really sorry about the inconvenience and hope we can find a good solution for you soon.

**Comment by Alexbits** [comment]
Thank you for your efforts @vinagesh! I'm considering the options.

**Comment by vinagesh** [comment]
@Alexbits - Here is an issue that I got the xamarin team to file and they are actively working on it - https://github.com/mono/mono/issues/20948. This does not ensure that there will not be issues with other APIs in .netstandard 2.1 but I have a high confidence it should unblock you to use the latest version of our SDK now. We are also working on coming up with a better strategy for handling mobile soon.

**Comment by Alexbits** [comment]
Hi @vinagesh! Thank you for an update. That is great news.

**Comment by Alexbits** [comment]
@viganesh I can confirm that reverting to the .NET Standard 2.0 did not help. I still get the exception unfortunately.

**Comment by vinagesh** [comment]
I heard the same from one more person. However, good news is that the bug is being fixed. You would need to upgrade you VS version to get the fix once the new version is released.

It should be in the next service release for Visual Studio 2019 v16.9.

https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmono%2Fmono%2Fissues%2F20948%23issuecomment-810205677&data=04%7C01%7Cvinagesh%40microsoft.com%7C0262c3d84efa419ca75908d8f3c4219e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637527370985254577%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3XSytdld6QhnGscpTgb6atlWIJYssWrLc296pm3BmQA%3D&reserved=0
