### ISSUE TITLE
[feature request] Ability to publish to/subscribe for any MQTT topic

### ISSUE THREAD

**Issue by kvasdopil** [Azure/azure-iot-sdk-csharp#1876]
Hi there.
Currently testing an MQTT broker feature available in latest preview version. One of my modules written in c# is using standard IoT features (twins, messages and methods) but I also need to have access to some arbitrary MQTT topics on a broker. Looks like there are several limitations:
- only one module client can be connected to edgeHub at a single time (so I cannot write my own client and use it along with a module)
- csharp sdk does not expose MQTT transport methods
- also there is no way to process incoming messages from user topics, message handler just produces error - https://github.com/Azure/azure-iot-sdk-csharp/blob/a0af7b7e03fadfc5f6d9c76ee7380eda4a92b7b2/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L615

**Comment by abhipsaMisra** [comment]
You are correct, there is [no official sdk support](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#level-of-support-and-limitations) for mqtt broker feature just yet; so for now you'll need to implement your own client. Since IoT Hub will not allow multiple connections of the same device/ module identity, you'll need to use your new client for all operations.

Since you are currently testing this feature you might already have a link to the public doc, but I am sharing it here as well for reference:
doc: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5
.NET sample: https://github.com/Azure-Samples/iot-hub-mqtt-5-preview-samples-csharp

**Comment by kvasdopil** [comment]
> Since you are currently testing this feature you might already have a link to the public doc, but I am sharing it here as well for reference:
> doc: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5
> .NET sample: https://github.com/Azure-Samples/iot-hub-mqtt-5-preview-samples-csharp

Interesting, the samples are for devices interfacing IoT hub, not for IoT modules communicating with broker. Also, as far as I know, MQTT 5 that is used in this samples is not supported in latest (1.2.0-rc4) runtime.

**Comment by abhipsaMisra** [comment]
It looks like you are looking for a sample that demonstrates communication with Edge hub, is that correct?
If so, then this item is on our backlog. While I cannot comment on any specific timelines, we are working to put such a sample out.

**Comment by ericmitt** [comment]
@kvasdopil we are working on mqtt sample for C#, no eta so far but will update this thread when ready.
For now the doc is available as preview: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11
Closing the issue for now.
