### ISSUE TITLE
[feature request] PnP APIs: ClientProperties can provide better abstraction of Plug and Play convention from device twin implementation details

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-csharp#2100]
### Issue
Some IoT Plug and Play developer tasks are still more complicated than they should be, and still require the developer to understand the inner workings of the device twin with respect to the IoT Plug and Play convention:

1. On device launch I need to know which properties have been updated while I was offline. The SDK is not helping with this at all. I need to go through all properties and compare version numbers on reported vs desired myself manually.
2. To ack property updates I need to create a whole new ClientPropertyCollection, create new properties, copy the value, set the status code and version. All things that are really device twin implementation details that the SDK could do for me. I would like to just receive the updated writable property and be able to call ack() on it – optionally provide a description and modify the value/status if needed.
3. Components are exposed as properties in the ClientPropertyCollection (device twin implementation detail!). To walk the collection and figure out the state of my properties I still need to know about device twin magic, like ‘__t’: ‘c’.

### Proposed Solution
ClientProperties should provide an abstraction over the device twin implementation details of the IoT Plug and Play convention. I would expect that ClientProperties understands the concept of components, and writeable properties (incl. the concept of ack'ing property updates).

**Comment by abhipsaMisra** [comment]
> 1. On device launch I need to know which properties have been updated while I was offline. The SDK is not helping with this at all. I need to go through all properties and compare version numbers on reported vs desired myself manually.

This is design. Since IoT hub does not preserve twin update notifications, it becomes the client's responsibility to fetch the twin and ensure that update notifications weren't lost. Since the SDK does not hold state in any form, this responsibility now shifts to the calling application. I'll updating our [ReconnectionSample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/DeviceReconnectionSample) to highlight this.
Adding this twin-sync logic to the SDK will also increase the bandwidth usage of the SDK since every reconnection attempt will then need to be followed by a call to retrieve the full twin. Since network traffic usage requirements and limitations vary per customer, we're leaving this logic to be implemented by the customer themselves, and are publishing a sample showing them how to do so.

> 2. To ack property updates I need to create a whole new ClientPropertyCollection, create new properties, copy the value, set the status code and version. All things that are really device twin implementation details that the SDK could do for me. I would like to just receive the updated writable property and be able to call ack() on it – optionally provide a description and modify the value/status if needed.

Thanks for suggesting this feature; this has been added in #2157 .

> 3. Components are exposed as properties in the ClientPropertyCollection (device twin implementation detail!). To walk the collection and figure out the state of my properties I still need to know about device twin magic, like ‘__t’: ‘c’.

Everything within a `ClientPropertyCollection` is a property, and it currently does not provide separate accessors for components. We're trying to keep the inspection of a returned twin to a minimum and hence haven't split components into its own "c# property". However, since the service will send the "__t": "c" identifier with each component-level property, it technically won't stop us from separating the properties into separate categories.
Having said that, the customer is always expected to know which components their devices are modeled against. With that information, they simply need to traverse the returned `ClientPropertyCollection` and handle each property appropriately. Since the component name is returned at the root -level, they can simply base their logic on that without having to inspect for the "__t": "c" identifiers.
Eg: https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/1a0cdd254ce1a3fe50ec99171c9bb3511b613704/iot-hub/Samples/device/ConventionBasedOperations/TemperatureController/TemperatureControllerSample.cs#L99

**Comment by wickste** [comment]
@abhipsaMisra Regarding 1: I understand it's the developers responsibility, but I expect the SDK to make this task easier. As it stands I have to iterate through all desired properties and compare their versions with the corresponding reported version. Then if there is a delta I need to send an ack. What I would expect is the SDK to give me a list of properties that need to be ack'ed. I don't see how the ReconnectionSample addresses the ack'ing of properties that got updated while the device was disconnected.

**Comment by abhipsaMisra** [comment]
@wickste @brycewang-microsoft has added some updates to the [ReconnectionSample](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/3f6bbe5bc59e1a7c54572960f25c9523cdb1d514/iot-hub/Samples/device/DeviceReconnectionSample/DeviceReconnectionSample.cs#L170-L177) to handle the scenarios where property updates could have been lost during a reconnection attempt. I think it should address the gap here but let me know if you'd like to see any additional pattern demonstrated in our sample.

**Comment by abhipsaMisra** [comment]
Closing this issue since the actionable items have been addressed.
