### ISSUE TITLE
[Bug Report] Unexpected ModuleClient.CloseAsync() behaviour

### ISSUE THREAD

**Issue by cjenp** [Azure/azure-iot-sdk-csharp#2118]
# Context

- Windows 10 Desktop x64
- .Net Core 3.1

Nugets used:
- Microsoft.Azure.Devices 1.34.0
- Microsoft.Azure.Devices.ProtocolGateway.Core 2.0.1
- Microsoft.Azure.Devices.ProtocolGateway.Providers.CloudStorage 2.0.1
- Microsoft.Azure.Devices.Client 1.37.2

## Description of the issue
In case we have a ModuleClient, that gets deleted (manually or by code) and we then want to use
the CloseAsync() method, I would then expect CloseAsync() to always fail (because the module does no longer exist) or to always work. Currently it looks like it depends on the last message sent to the IoT hub, so it sometimes throws and sometimes not. Please look at the code bellow. If you remove the SendEventAsync() inside the try block it will work fine, if you leave it it will throw.
Is this by design?

## Code sample exhibiting the issue

```
static async Task Main(string[] args)
{

    var iotHubHostName = "YourIoTHubHostname";
    var hubConnectionString = "IoTHubConnectionString";

    var deviceId = "UnitTestDevice";
    var moduleId = "MyModule";

    var registryManager = RegistryManager.CreateFromConnectionString(hubConnectionString);
    
    var module = await registryManager.AddModuleAsync(new Module(deviceId, moduleId));
    var moduleConnectionString = GetModuleConnectionString(iotHubHostName, deviceId, module);
    var moduleClient2 = ModuleClient.CreateFromConnectionString(moduleConnectionString, TransportType.Mqtt);
    await moduleClient2.SendEventAsync(new Message());

    //Delete the module
    await registryManager.RemoveModuleAsync(deviceId, moduleId);

    try
    {
        await moduleClient2.SendEventAsync(new Message()); // If you remove this part then CloseAsync() will not throw
    }
    catch
    {
    }
    finally
    {
        await moduleClient2.CloseAsync();
        moduleClient2.Dispose();
    }
}

private static string GetModuleConnectionString(string hostName, string deviceId, Module module)
{
    return $"HostName={hostName};DeviceId={deviceId};ModuleId={module.Id};SharedAccessKey={module.Authentication.SymmetricKey.PrimaryKey}";
}
```

**Comment by abhipsaMisra** [comment]
Could you share some additional details on the exception that you see on calling `SendEventAsync()`? 

Since your client was previously connected, deleting the identity would cause service to drop the client's connection, albeit with a certain buffer. As a result, if you try to initiate an operation on this connection, Id expect you to see a difference in behavior based on the operation initiated.

- calling CloseAsync() after immediately deleting a module identity will result in the connection being closed by the client-side. The end result here is that service receives a closure request from the device application and honors the request, hence you do not see any exceptions being thrown.
- calling SendAsync() after immediately deleting a module identity will result in the client attempting to send publish packets to the service. On receiving any such packet for an already deleted identity, service will reject the packet and close the connection. I expect this to surface to the SDK as a disconnection event, which would be followed by a reconnection attempt. At this point, once the device app tries to authenticate a deleted module identity, I'd expect the auth to fail and the device application to receive an exception.

Is there a specific scenario that you are attempting to achieve with this flow?

**Comment by cjenp** [comment]
The exception I get on SendEventAsync() and CloseAsync():
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: 'CONNECT failed: RefusedNotAuthorized'.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<CloseAsync>d__75.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<CloseAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.InternalClient.<CloseAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.Program.<Main>d__0.MoveNext() in C:\Users\xy\GitRoot\ConsoleApp1\ConsoleApp1\Program.cs:line 41

Which is what I would expect to get every time I try to do something with a ModuleClient that does not exist anymore. But CloseAsync() does not behave this way. It only throws if there was a call to SendEventAsync() before that.

In my scenario I have 2 services, Service1 is in charge of deleting/creating devices and modules and Service2 is basicly a device emulator that uses ModuleClient to emulate modules. Now while the emulator is running and sending messages with SendAsync() Service1 notifys Service2 that the module has been deleted. Service2 then uses CloseAsync and Dispose on the ModuleClient to clean up. And this clean up throws, sometimes. Like I described above it fails if there was a SendEventAsync() between the deleting of the module on Service1 and calling of the CloseAsync() on Service2. If there was no SendEventAsync() in between then everything works fine. 

I allready resolved my issues by simply removing CloseAsync(). But in my opinion SendEventAsync() should not have the side effect of causing the call to CloseAsync() to throw. It should either throw allways when the module does not exist anymore, or not throw at all when the module does not exist anymore.

**Comment by abhipsaMisra** [comment]
I understand your concern, but I'd like to highlight a couple of things at play here:

> Which is what I would expect to get every time I try to do something with a ModuleClient that does not exist anymore. But CloseAsync() does not behave this way. It only throws if there was a call to SendEventAsync() before that.

The issue here is not `CloseAsync()` behaving differently if it is accompanied by a previous `SendEventAsync()` call, but rather depends on the state of the client when `CloseAsync()` itself is called.
Let me take you through the state of the client after module deletion, and hopefully that'll help understand this a bit better.

1. You have an established connection between your module client and service. This connection has already been authenticated successfully over MQTT and is currently active.
2. You have a service that deletes the module identity that was connected in step 1. 
3. Once your service deletes this identity, IoT hub will perform a background check to see if this module identity has any currently open sessions. If yes, then it will terminate the connection.
4. The SDK will detect this loss of connection and notify the client that it has been disconnected (`Connection status changed: status=Disconnected_Retrying, reason=Communication_Error`).
5. It will try to reconnect. 
6. Any subsequent requests to authenticate a connection with the above module identity will fail with an MQTT ConnAck code of `RefusedNotAuthorized`.
7. The SDK will identify this as a non-retryable error scenario, will report a connection status change (`Connection status changed: status=Disconnected, reason=Bad_Credential`) and will stop retrying.
8. Any subsequent operations will result in an `UnauthorizedException` being thrown.

Based on the data you've shared, I'm inclined to say that the difference in behavior you're seeing has to do with the delay between step 3 completing and your application calling `CloseAsync()`, and not whether `SendEventAsync()` is called or not.

If you call `CloseAsync()` immediately after the module identity has been deleted but before service was able to detect and initiate a remote disconnect (which should be a couple of milliseconds), then the behavior you'll see is the client initiating the connection closure and service complying. However, if you initiate the client close after service has initiated the disconnect, you'll see the request failing with an `UnauthorizedException`. 

An easy way to test this out would be to add a delay of a couple of milliseconds before your call to `CloseAsync()` (with `SendEventAsync()` commented out), and you should be able to see an `UnauthorizedException` being thrown.

**Comment by abhipsaMisra** [comment]
Also, for the connection status change events that I am talking about in step 4 and step 7, you can subscribe to those via the `SetConnectionStatusChangesHandler` callback.

```csharp
moduleClient.SetConnectionStatusChangesHandler((status, reason) =>
{
    _logger.LogInformation($"Connection status changed: status={status}, reason={reason}.");
});
```

**Comment by cjenp** [comment]
I tested it out with adding a delay instead of the SendEventAsync(), and you are correct. It makes sense now. Sorry for any inconvenience caused and thank you for explaining @abhipsaMisra 🙂
