### ISSUE TITLE
[Bug Report] DeviceClient.OpenAsync: CancellationToken not effective when offline

### ISSUE THREAD

**Issue by its-phil** [Azure/azure-iot-sdk-csharp#2236]
# Context

- **OS, version, SKU and CPU architecture used:** Ubuntu 18.04 x86
- **Application's .NET Target Framework :** net5.0
- **SDK version used:** 
  - Microsoft.Azure.Devices.Client 1.39.0
  - Microsoft.Azure.Devices.Provisioning.Transport.Amqp 1.16.0

## Description of the issue
This is a follow-up issue on #2036.

Calling `DeviceClient.OpenAsync` with a cancellation token ignores the token timeout if the device is offline (tested on an Azure VM where all outbound connections are blocked). I would expect `OpenAsync` to cancel if I set the cancellation token source timeout to e.g. 15 seconds. Instead, the timeout is always 1 minute. 

My first issue about this topic (#2036) was solved by adding the `TimeSpan` to the `ProvisioningDeviceClient` in this release: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-8-11. However, this option doesn't seem to be available in the DeviceClient. Is there another way to work around this issue? I'd like the `OpenAsync` call to fail faster when the device is offline.

## Code sample exhibiting the issue
```cs
Console.WriteLine("Connecting to IoT Hub... ");
var authenticationMethod = new DeviceAuthenticationWithRegistrySymmetricKey(deviceId, primaryKey);
var transportType = TransportType.Amqp_Tcp_Only;
const int timeoutMs = 15000;
using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(timeoutMs));

DeviceClient? dc = null;
try
{
    sw.Start();
    dc = DeviceClient.Create(iotHubAddress, authenticationMethod, transportType);
    await dc.OpenAsync(cts.Token);
    Console.WriteLine("OK");
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
    Console.WriteLine(ex.InnerException?.Message);
}
finally
{
    sw.Stop();
    await dc?.CloseAsync();
    Console.WriteLine($"connection succeeded or cancelled after {sw.ElapsedMilliseconds} ms.");
    // Here I'd expect ~15 seconds. Instead I always get ~60 seconds.
}
```

**Comment by azabbasi** [comment]
@its-phil 
Thanks for reaching out to us regarding your issue.

Unfortunately, this is a known issue to the DeviceClients that are configured with AMQP protocol. 
Historically speaking, the underlying AMQP library the SDK used did not accept cancellation tokens and the SDK uses a configurable operation timeout that has a 60-second default timeout. 

The AMQP library has since fixed the issue and we have updated our SDK to respect these cancellation tokens. This change has not been published yet but it will be released with our next SDK version release.
You can see the PR here: #2216

If this is a blocking issue and you can't wait for the next release, you can set the `OperationTimeout` to be 15 seconds (I see that is your configured timespan on the cancellation token) on the `AmqpTransportSetting` when you are initializing your device client.

Please let me know if that works for you or you need any further assistance.

**Comment by its-phil** [comment]
@azabbasi Thanks for your reply and explanation. For the moment I can live with the 60 second default value. I look forward to the next release where the CancellationTokens will be respected. Can you give an estimate when the next SDK release is due?

**Comment by azabbasi** [comment]
@its-phil 
I would say in a couple of weeks maybe. We don't have a fixed release schedule but we will try to put up a release as soon as we can. Thanks for your patience.
