### ISSUE TITLE
Recreate device client without ConnectionForcefullyClosedOnNewConnection error

### ISSUE THREAD

**Issue by ChangeTheCode** [Azure/azure-iot-sdk-csharp#2332]
I have the scenario that my IoT Device gets an SAS token from the cloud which expired after 30 minutes. If this will close to be happen the device now to request a new SAS token from the cloud. After receiving this token the client will recreate a new deviceClient by using the factory `DeviceClient.CreateFromConnectionString(String, TransportType)`  [Link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.createfromconnectionstring?view=azure-dotnet#microsoft-azure-devices-client-deviceclient-createfromconnectionstring(system-string-microsoft-azure-devices-client-transporttype). 

When I call this method I got an exception ( ConnectionForcefullyClosedOnNewConnection  error code: 400027) with the already existing and also used instance. Is there any possibility to recreate a device client without getting such error. 

From my point of view I can't close the client before because I want to have less as possible connection lost between device and IoT Hub. Because I can handle messages on the device but not  the interaction between Cloud to device or is it an "issue" by design in case I use SAS token which are provided by cloud. 

I know there is a DPS service which is designed to handle the initial connection of the IoT device but the solution was build at a time there wasn't anything like an DPS.

Is there any possibility to switch the SAS token form an deviceClient instance or use the SAS Token from the ClientOptions [SasTokenTimeToLive](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.clientoptions.sastokentimetolive?view=azure-dotnet#microsoft-azure-devices-client-clientoptions-sastokentimetolive)?

**Comment by brycewang-microsoft** [comment]
Hi @ChangeTheCode ,
As you may notice, `ConnectionForcefullyClosedOnNewConnection` occurs when another client creates a new connection to IoT Hub using the same identity ([reference](https://docs.microsoft.com/bs-latn-ba/azure/iot-hub/troubleshoot-error-codes#400027-connectionforcefullyclosedonnewconnection)). As you were trying to create another connection to your device with a new SAS token while the about-to-expire one was still there, this could be expected. 

If you are using MQTT, due to the requirement "having as less as possible connection lost", you should consider using AMQP protocol instead, which will proactively renew the SAS token prior to its expiration.

For `ClientOptions`, you can use it with `SasTokenTimeToLive` & `SasTokenRenewalBuffer` (to configure the time to live and renewal buffer value for generated sas tokens) in the initial creation of device client via `CreateFromConnectionString()`. This should be a good replacement for your current token management approaches.

**Comment by brycewang-microsoft** [comment]
Here is the method `CreateFromConnectionString()` you may need:
https://github.com/Azure/azure-iot-sdk-csharp/blob/40ad37c4df9537757bcf1438520ed56a27f35a93/iothub/device/src/DeviceClient.cs#L159

**Comment by brycewang-microsoft** [comment]
@ChangeTheCode 
Hope my answer can help address your questions. Feel free to reopen this one if you have any related issues/questions further!
