### ISSUE TITLE
[Bug Report] AmqpAuthenticationRefresher: Odd disposal/cancel behavior (ObjectDisposedException)

### ISSUE THREAD

**Issue by rgrace-puck** [Azure/azure-iot-sdk-csharp#2339]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 x64
- **Application's .NET Target Framework :** net48
- **Device:** Azure App Service
- **SDK version used:** 1.40.0 (Microsoft.Azure.Devices.Client)

## Description of the issue
To preface this, the usage pattern described in this issue is unusual and we're aware of that but I believe this issue still affects other consumers of this SDK.

We have a web app which creates a short lived `DeviceClient` (<=60s alive) and sends messages back to our field equipment via an API controller. When deployed, we start to see `ObjectDisposedException` (thousands per hour) in our Application Insights logs after an extended period of time (usually ~20-30 minutes). We do have a try/catch block around the IoT Hub operations but this exception is not caught there. 

After doing some investigation/testing, using `ReceiveAsync(CancellationToken)` (instead of the TimeSpan equivalent) and manually cancelling before disposal of the client yielded no errors. 

## Additional notes
Looking at the internals of the library, it seems the behavior of using `TimeoutHelper` to generate a cancellation token is flawed with `AmqpTransportHandler` in combination with the refresh loop behavior in `AmqpAuthenticationRefresher`. 

For example, there is a method in `AmqpAuthenticationRefresher` called `StopLoop` but this method doesn't seem to do anything except log that it was called. 

These are very basic findings from glancing at the repository so it may be lacking context / inaccurate.

## Code sample exhibiting the issue
NOTE: This is a simplified version and not the actual code we're using but is effectively the same operation.
```cs
using Microsoft.Azure.Devices.Client;
using System;
using System.IO;
using System.Threading.Tasks;

namespace iot_test
{
    public class TestController
    {
        private static AmqpTransportSettings GetAmqpTransportSettings()
        {
            return new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
            {
                AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings
                {
                    Pooling = true,
                    MaxPoolSize = 1
                },
                OpenTimeout = TimeSpan.FromSeconds(5),
                OperationTimeout = TimeSpan.FromSeconds(5)
            };
        }

        private static readonly ITransportSettings[] TransportSettings = { GetAmqpTransportSettings() };

        public async Task<string> ReceiveCommandControllerMethod()
        {
            Message message = null;
            DeviceClient deviceClient = null;

            string deviceConnectionString = "iot_device_connection_string";

            try
            {
                deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportSettings);
                deviceClient.SetRetryPolicy(new NoRetry());
                deviceClient.OperationTimeoutInMilliseconds = 3000;

                message = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(60));

                if (message == null)
                {
                    return string.Empty;
                }

                await deviceClient.CompleteAsync(message);

                using (var sr = new StreamReader(message.GetBodyStream()))
                    return await sr.ReadToEndAsync();
            }
            catch (Exception)
            {
                // Log error
            }
            finally
            {
                message?.Dispose();

                if (deviceClient != null)
                {
                    await deviceClient.CloseAsync();
                    deviceClient.Dispose();
                }
            }

            return string.Empty;
        }
    }
}
```

## Console log of the issue
```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. The authentication method instance has already been disposed, so this client is no longer usable. Please close and dispose your current client instance. To continue carrying out operations from your device/ module, create a new authentication method instance and use it for reinitializing your client.
Object name: 'DeviceAuthenticationWithSakRefresh'. 
```

```
System.AggregateException:
System.ObjectDisposedException:
   at Microsoft.Azure.Devices.Client.AuthenticationWithTokenRefresh+<GetTokenAsync>d__19.MoveNext (Microsoft.Azure.Devices.Client, Version=1.40.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpIotCbsTokenProvider+<GetTokenAsync>d__3.MoveNext (Microsoft.Azure.Devices.Client, Version=1.40.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1+<>c.<CallTask>b__24_1 (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Amqp.AsyncResult.End (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Amqp.AmqpCbsLink+<>c.<SendTokenAsync>b__5_1 (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpIotCbsLink+<SendTokenAsync>d__2.MoveNext (Microsoft.Azure.Devices.Client, Version=1.40.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher+<RefreshLoopAsync>d__10.MoveNext (Microsoft.Azure.Devices.Client, Version=1.40.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
```

**Comment by rgrace-puck** [comment]
UPDATE:
We're still seeing this exception even when using the cancellation overload for `ReceiveAsync`, there was a misconfiguration with our test setup that caused it not to log. Re-running this test with proper configuration is still showing the `ObjectDisposedException`

**Comment by cjenp** [comment]
Is there any update regarding this issue? It seems we are having a similar problem for the last ~20 days (started on 27.3.2022 at around 3 PM (GMT+2)). Our use case is a bit different: we have a protocol gateway that enables our legacy devices to communciate with IoT Hub. So there is usually around 1200 DeviceClients connected. After around 1h the ObjectDisposedException start appearing in the logs. I am still looking into the issue and collecting data, so i dont have the details/example yet

**Comment by abhipsaMisra** [comment]
Thanks for bringing this to our attention @rgrace-puck and @cjenp ; I'm looking into this issue now. 
@rgrace-puck In our application, is there a single device identity configured at any point or do you initialize multiple devices identities throughout your application? I'm trying to understand your reasoning for turning on the connection pooling feature. Are you device/devices connecting through a device specific connection string or are you using an IoT hub scope level connection string?

@cjenp You've mentioned that you have multiple device identities connecting over a protocol gateway of sorts. This is a scenario where we generally expect connection pooling to be turned on but I would like to confirm that explicitly. I've got the same connection string related question for you as well - are you device/devices connecting through a device specific connection string or are you using an IoT hub scope level connection string?

I'm looking for the above information because the token refresher disposal happens differently for connection-pooled clients vs for non-connection-pooled clients.
Thanks!

**Comment by cjenp** [comment]
We are using connection pooling and an IoT hub scope level connection string.

I have done some extensive testing in the last days. Currenlty it looks like our problem is not with Microsoft.Azure.Devices.Client but with the Microsoft.Azure.Devices.ProtocolGateway.Core library. We are using a custom event listener that also listen to the "Microsoft-Windows-DotNETRuntime" event source, and we noticed a lot of the ObjectDisposedExceptions mentioned by @rgrace-puck there (they also started to appear right at the time that our protocol gateway stoped working). I later wrote a simple emulator that used only the DeviceClient part of our code and simulated 1000 devices on my local PC for a few hours.
Since there were no issues, we are now suspecting the Microsoft.Azure.Devices.ProtocolGateway.Core library.

Anyway, we are in the process of replacing the protocol gateway library part to eliminate the problems. So everything is ok for now :slightly_smiling_face: Sorry if I caused you any inconvenience @abhipsaMisra

**Comment by abhipsaMisra** [comment]
@cjenp Not a problem, I'm glad to hear that you are now unblocked. One point I'd like to highlight is that we don't recommend using IoT hub scope level connection strings in production applications because they come with some security risks. In the off-chance that this connection string gets leaked then your entire IoT hub infrastructure gets exposed. A better alternative for managing authentication for groups of client identities would have been to use X509 group certificates however X509 authenticated clients don't support connection pooling. For your scenario, using device scope connection strings would be the safest option.

@rgrace-puck Thank you for explaining your scenario. Using multiple device identities authenticating with their own individual shared access keys and pooled over a single connection should not be showing this exception, even with your aggressive disposal and recreation policy. Would you be able to collect and share the SDK logs for an instance where you hit this [error](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs)?

**Comment by rgrace-puck** [comment]
Absolutely. I cannot guarantee when I'll have these logs collected, though.

Just wanted to mention this issue isn't actually having an effect on our application, just filling up our app insights logs. We've been using this SDK in production for about a month now with no other issues.

**Comment by rgrace-puck** [comment]
@abhipsaMisra I ran a local test while collecting logs and observed about 1,000 `ObjectDisposedException`'s, is there a preferred way of sharing the etl file? It's about 446 MB in size.

**Comment by abhipsaMisra** [comment]
Thank you @rgrace-puck , I'll review your logs.

For your application logic, is there a reason why you're opting to recreate the client for each request? AMQP protocol can be opened once and then used to send multiple messages over the lifetime of the connection, so you might be able to reduce the open-close stress on your application and decrease the number of times you're having to open the connection for a single client.

**Comment by rgrace-puck** [comment]
Yes, our application is scaled horizontally (multiple instances) which means there would be multiple active DeviceClient's for the same device.

Previously, we had it setup like that and saw exceptions related to AMQP resource contention (e.g. link-creation-conflict) and opted for our current approach instead.

**Comment by abhipsaMisra** [comment]
I see. We don't generally recommend using AMQP as a single request-response protocol (like HTTP), but if this approach works for you then its ok. This model is unlikely to cause odd disposal behavior though, so I'll be investigating that separately anyway.

For horizontal scaling I'd like to call out that you'll need to ensure in your application logic that you're trying to initialize only a single client for a particular device identity at any point. This is because service will allow only a single connection from a device identity at any point in time. (I think you already would have this logic in place else you would have encountered a host of other errors by now, but I'd like to call this out anyway).

**Comment by abhipsaMisra** [comment]
@rgrace-puck I'm looking at the etl file you shared and I can't locate any of the exceptions. Do you have a timestamp of the period when you saw these exceptions? It's possible that since there were a lot of log entries generated I'll need to filter out the logs to a narrower time range to find this specific exception.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/22563986/169577396-95676370-fbd5-4398-92d8-39bce9b59b53.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/22563986/169577406-184b4db1-f3bf-4214-a075-10f7c7b40760.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/22563986/169577416-49a8c759-4a46-41d9-8a3f-7c6965bafddc.png)

I also have a question around your retry policy. I see from the code snippet that you have the SDK's default retry policy turned off. What process do you follow for recovery on encountering an exception? Do you attempt any retries for the `ReceiveAsync()` operation or do you discard the attempt if you encounter an exception?

**Comment by rgrace-puck** [comment]
I don't have an exact timestamp, but I know the exceptions happened towards the end of the logging session. I terminated the test/session shortly after noticing the exceptions.

Our retry policy is to discard the attempt and retry on the next request from our equipment.

**Comment by abhipsaMisra** [comment]
I found some gaps in our logging statements which is why I wasn't able to locate any instances of exceptions being thrown in the logs that you shared. The etl file, however, does highlight that `AmqpIotCbsTokenProvider.GetTokenAsync` is getting called 10487 times, whereas `AuthenticationWithTokenRefresh.GetTokenAsync` was successful in generating tokens only 7437 of those times.

I'm adding some additional logging to trace the flow a bit better; what would be the best way to share the updated sourcecode with you? If you'd like I could share an unsigned nuget with you for you to try out, or you could directly build from our sourcecode. Let me know what works for you and thanks for working on this with us!

**Comment by rgrace-puck** [comment]
An unsigned nuget package would probably work best, thanks!

**Comment by abhipsaMisra** [comment]
I'm unable to upload a nuget package to GitHub. Would you be able to send me an email to "abhipsa dot misra at microsoft dot com" and I can then share the packages over email.

**Comment by abhipsaMisra** [comment]
The logging additions will be released as a part of our next official release. I don't have a date for it at the moment, though.

**Comment by abhipsaMisra** [comment]
The new nuget package with these logs has now been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-07-26
Please try out the new newer version, and if the issue still persists, please share the SDK logs. I do want to call out that we haven't added any changes around the token refresher implementation specifically, though.

**Comment by rgrace-puck** [comment]
I've run a second test and the exceptions did show up again. Same behavior as previously documented.
Please see your email for the ETL file (450 MB in size).

**Comment by abhipsaMisra** [comment]
Thanks for sharing the logs. I can see the ObjectDisposedException being logged from about 10:13 up until 10:44. I'm investigating the logs and will get back to you on this.

**Comment by rgrace-puck** [comment]
I upgraded Microsoft.Azure.Devices.Client to 1.41.3 and ran the same test for a couple hours.
No exceptions were observed in the logs so it seems like the issue was fixed!

It has yet to be deployed to a production environment but I don't foresee any issues cropping up from that.
I will re-open this issue if anything comes up. Thanks!
