### ISSUE TITLE
System.Net.Sockets.SocketException: The socket has been shut down

### ISSUE THREAD

**Issue by JokerstudioDev** [Azure/azure-iot-sdk-csharp#247]
- OS and version used: iOS 11.1

- SDK version used: Microsoft.Azure.Device.Client 1.6.0

# Description of the issue:
I use Microsoft.Azure.Device.Client in Xamarin.iOS. When my iphone become to lock screen then websocked is shutdown automatic my app crashes and internal exception library is "System.Net.Sockets.SocketException: The socket has been shut down". How to handle this problem because i can't control hardware?

**Comment by CIPop** [comment]
Most application environments such as Android, iOS and UWP have some mechanism to allow (for limited time in order to conserve battery) running code in the background.
I found the following that may help solve this issue:
* https://developer.apple.com/library/content/technotes/tn2277/_index.html 
* https://developer.xamarin.com/guides/ios/application_fundamentals/backgrounding/ios_backgrounding_techniques/ios_backgrounding_with_tasks/

Closing as not related to the Azure SDK.

**Comment by JokerstudioDev** [comment]
Thank you for your solution.
