### ISSUE TITLE
Version policy for preview NuGet packages

### ISSUE THREAD

**Issue by stefan2410** [Azure/azure-iot-sdk-csharp#278]
Nuget  proposes update of Microsoft.Azure.Devices.Client from 1.6.0-preview-001  to 1.6.0.
I updated and  there are  changes in API  from 1.6.0-preview-001  (TwinCollection in my case)
and  exceptions in Service Fabric application for dependencies.
Should I update or not?

Version | Downloads | Last updated

1.6.0 (current version) | 267 | 3 days ago
1.6.0-preview-001 | 1,550 | 24 days ago
1.5.2 | 7,114 | a month ago

**Comment by CIPop** [comment]
You should not update if you're experimenting with preview features. 
What do you mean by "Nuget proposes update"? Could you please add a screen-shot?

@tameaw @jasmineymlo - This is the confusion we've talked about offline: 1.6.0 release should be the release of 1.6.0-preview. In the future, we could instead allocate a higher number for -preview maybe?

**Comment by stefan2410** [comment]
![deviceclient](https://user-images.githubusercontent.com/1259393/33785993-0c8b14d2-dc70-11e7-8cd9-57d3e844d89e.PNG)

**Comment by CIPop** [comment]
Thanks @stefan2410 ! 

@jspaith, @tameraw we need to reconsider our versioning practices in such a way that NuGet doesn't recommend upgrading until we have actually released the `-preview` feature.

**Comment by CIPop** [comment]
I have 2 recommendations (further discussion is required):

1. Use preview versions such as 0.9.n-preview for features where the preview period is long (either no ETA or ETA is >2 weeks). The downside is that an upgrade will always be offered although most people will not take a dependency on the -preview since it starts as a lower version than the current version.
2. Reserve preview versions. E.g. in this case we could have used 1.10.0-preview for Modules. The downside here is that we may need to skip certain versions when we actually release the package, or we may end up not reserving enough versions to allow for SDK updates prior to the new feature release.

**Comment by CIPop** [comment]
Hello @stefan2410 , we've closed on this discussion and decided we'll try to follow option 2 going forward. 
/cc @tameraw @yzhong94
