### ISSUE TITLE
[Bug Report] - ulong values in object cause UpdateReportedPropertiesAsync to hang

### ISSUE THREAD

**Issue by tank104** [Azure/azure-iot-sdk-csharp#2958]
# Context

- Windows 11 Professional x64,
- .NET 6 Framework 
- SDK "previews/v2" branch (latest)
- Device is Laptop

if the json contains a ulong value UpdateReportedPropertiesAsync hangs, and doesn't report any errors that I can see (tried turning on Trace too).  Setting the ulong to 0 works.

## Code sample exhibiting the issue
```
   var _deviceClient = new IotHubDeviceClient(ConnecitonString);
    var deviceInformationProperties = new Dictionary<string, object>
    {
      { "serialNumber", 5283920058631410000  }
    };
    var reportedProperties = new ReportedProperties
    {
      { "test", properties }
    };
    await _deviceClient.UpdateReportedPropertiesAsync(reportedProperties);

```

## Console log of the issue
Log attached (renamed from ETL to LOG so I can attach)

[iot_000001.log](https://github.com/Azure/azure-iot-sdk-csharp/files/10007403/iot_000001.log)

**Comment by abhipsaMisra** [comment]
Thanks for bringing this to our attention.
It looks like the SDK is incorrectly handling this "bad request" and is attempting to retry the operation, which is why the application looks like it is hanging. We'll put a fix in for this.

For reference, twin property integer values need to be between -4503599627370496 and 4503599627370495.
Ref: https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format

The actual error message: 
{"errorCode":400004,"trackingId":"ca254def40b049bd8fd468483787a8f4-G:0-TimeStamp:11/14/2022 22:52:27","message":"Argument 'serialNumber' value must be between '-4503599627370496' and '4503599627370495'. The provided value was '5283920058631410000'.","timestampUtc":"2022-11-14T22:52:27.7262459Z"}

**Comment by tank104** [comment]
Thanks @abhipsaMisra - error would be perfect.  For now I am converting those to string.

**Comment by abhipsaMisra** [comment]
This has been released in https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2023-02-09-v2preview
