### ISSUE TITLE
[Bug Report] [v2-preview] How to send Payload as byte array to IoTHub and receive Payload as byte array

### ISSUE THREAD

**Issue by bastyuchenko** [Azure/azure-iot-sdk-csharp#3218]
Hello,
I switched from SDK v1 to SDK v2 and it looks like SDK v2 supposes that c2d and d2c message's payload is always string typed. 
But in our project

- we use protobuf contract as contract between "device" and "cloud"
- c2d and d2c message's payload type is byte[]. After receiving byte[] I translate it to .NET type generated from protobuf contract.
- message.ContentType should be "application/protobuf"

**Comment by bastyuchenko** [comment]
If I'm trying to receive message from IoT Hub, I expects that I can receive Payload as byte[] and convert it to .NET type.
But I can do it because _payload is private field and TryGetPayload method always convert payload to string - https://github.com/Azure/azure-iot-sdk-csharp/blob/f7bec7d78535dff52200a8f581e2710968e34e4a/iothub/device/src/Messaging/IncomingMessage.cs#L170

**Comment by drwill-ms** [comment]
Hi @bastyuchenko we've been looking for customers who wish to use binary payloads - thanks for reaching out and sharing your scenario.

In v2, we provided a new mechanism for customers to choose which JSON library they wanted to use, rather than us hard-coding Newtonsoft.Json. Some operations, like C2D, didn't care and had you work directly in bytes, which was inconvenient for everyone who uses JSON.

A member of our team, @rido-min, has been a proponent of enabling binary payloads and has looked at this feature too. He tried to implement a `PayloadConvention` with Protobuf and showed where he had trouble. In trying to accommodate that, we've introduced a few changes (#3189):

- Simplify the `PayloadConvention` to just serialize and deserialize. Encoding and serialization as separate steps are not necessary for all formats.
- Surface the byte array on types such as `IncomingMessage` and `DirectMethodRequest`. If you wish to bypass the client-configured serializer for a specific operation, you can do that by accessing the bytes directly.

One big problem we ran into is that some IoT hub operations **require** JSON, like Twin. The notion that a single, generic payload serializer can be configured on a client may not be realistic. A custom payload serializer may need to interrogate the payload several different ways to see what type it is - and that isn't ideal.

We'll have a new version of the preview out with these changes. Perhaps you can try them out and let us know how they work for you. I would try to get a preview out today if that fits your schedule.

**Comment by bastyuchenko** [comment]
Hi @drwill-ms 
I tried previews/v2
Now I narrowed 3 to 1 class
```
public class MyPayloadConvention : PayloadConvention
    {
        public static readonly MyPayloadConvention Instance = new MyPayloadConvention();

        public override byte[] GetObjectBytes(object objectToSendWithConvention)
        {
            if (objectToSendWithConvention is ProtoBufSecureMessage ss)
            {
                return ss.ToByteArray();
            }

            throw new Exception(
                "It is not ProtoBufSecureMessage type message.");
        }

        public override T GetObject<T>(byte[] objectToConvert) => throw new NotImplementedException();

        public override T GetObject<T>(Stream streamToConvert) => throw new NotImplementedException();

        public override T GetObject<T>(string jsonObjectAsText) => throw new NotImplementedException();

        public override string ContentType => "application/protobuf";

        public override string ContentEncoding => Encoding.UTF8.WebName;
    }
```
Maybe it is better to have 
`byte[] GetObjectBytes<T>(T objectToSendWithConvention)`
instead of 
`byte[] GetObjectBytes(object objectToSendWithConvention)`

**Comment by drwill-ms** [comment]
@bastyuchenko can you help me understand why `<T>` would make a difference? How would you implementation be different?

**Comment by bastyuchenko** [comment]
@drwill-ms, correct me if I'm wrong but isn't it boxing/unboxing here if we use object as input parameter in the method
`byte[] GetObjectBytes(object objectToSendWithConvention)`
Please see explanation here https://stackoverflow.com/a/4424049

**Comment by drwill-ms** [comment]
You have a point. I figured Newtonsoft.Json and System.Text.Json never cared so why should we? They take `object` as a parameter.

Although upon checking I see that STJ (in .NET 6+) has a `<T>` overload.

Anyway, I think we've realized we can't really support binary payloads using the `PayloadConvention` strategy because some IoT hub operations must be JSON. So the approach we're taking is exposing the byte[] directly for operations where you can choose to use a binary paylaod.

**Comment by bastyuchenko** [comment]
Hi @drwill-ms 
I'd like to return to the current possible solution to implement my own PayloadConvention.
```
public class MyPayloadConvention : PayloadConvention
    {
        public static readonly MyPayloadConvention Instance = new MyPayloadConvention();

        public override byte[] GetObjectBytes(object objectToSendWithConvention)
        {
            if (objectToSendWithConvention is ProtoBufSecureMessage ss)
            {
                return ss.ToByteArray();
            }

            throw new Exception(
                "It is not ProtoBufSecureMessage type message.");
        }

        public override T GetObject<T>(byte[] objectToConvert) => throw new NotImplementedException();

        public override T GetObject<T>(Stream streamToConvert) => throw new NotImplementedException();

        public override T GetObject<T>(string jsonObjectAsText) => throw new NotImplementedException();

        public override string ContentType => "application/protobuf";

        public override string ContentEncoding => Encoding.UTF8.WebName;
    }
```

I believe it's not clear for a developer what each method in this payload does without dive in the source code. `PayloadConvention` has 3 methods with the same name `GetObject` that are mandatory to override.
`public abstract T GetObject<T>(Stream streamToConvert)` - only to processing payload of Twin
`public abstract T GetObject<T>(byte[] objectToConvert);` - to processing payload of DirectMethod, IncommingMessage and again Twin
`public abstract T GetObject<T>(string jsonObjectAsText);` - looks like is used in `public abstract T GetObject<T>(byte[] objectToConvert);`  :confused:

As you mentioned it would be better to have separate "Convention" for each feature, something like

- IncommingMessagePayloadConvention
- TwinPayloadConvention
- DirectMethodPayloadConvention

But... let's imagine a situation when a device should consume various payload type comes to IoT Hub (maybe from different "services"). Should this device initiate and manage several IotHubDeviceClient ?

**Comment by drwill-ms** [comment]
> I believe it's not clear for a developer what each method in this payload does without dive in the source code. PayloadConvention has 3 methods with the same name GetObject that are mandatory to override.

That's a good point. I'll add some documentation for these methods.

Upon doing that I realize that 2 of the `GetObject<T>` overloads are only needed by the SDK by the `DefaultPayloadConvention`, so I've opened a PR to remove them from the `PayloadConvention` abstract class.

> As you mentioned it would be better to have separate "Convention" for each feature

The team had a discussion about it this morning and decided, based on what we've realized about the nature of non-JSON support throughout IoT hub, we'll choose to keep `PayloadConvention` for JSON use only and rely on the `GetPayloadBytes` methods we've added to `IncomingMessage` and `DirectMethodRequest` for folks wanting to use binary payloads. We feel that is about the same as v1 for binary payloads and for JSON users which we expect are the vast majority, the new API surface makes it a lot easier.

For now, we don't want to make the API more complicated than it has to be and we have wiggle room for the future to add operation-based payload convention settings.

**Comment by bastyuchenko** [comment]
> we'll choose to keep PayloadConvention for JSON use only and rely on the GetPayloadBytes methods we've added to IncomingMessage and DirectMethodRequest for folks wanting to use binary payloads. 

good, I got your point, it makes sense. Just give me to know once the change regarding separation is merged to previews/v2.

**Comment by drwill-ms** [comment]
I merged the change in to removes those 2 extra method overloads and added more documentation. We don't plan to ship another preview again, necessarily. We're inching very close to final release, doing long haul testing and addressing issues that would keep a device running indefinitely.

Thank you so much for your insights, ideas, and pushback. We **really** appreciate your passion and presence.
