### ISSUE TITLE
IoT Edge v2 - Not showing connected

### ISSUE THREAD

**Issue by grtn316** [Azure/azure-iot-sdk-csharp#324]
Hello,

I have iot edge version 2 running in ubuntu. When navigating to the "Management" tab, the device shows disconnected and does not display a lastactivitytime or lastconnectionstateupdatedtime. When I switch to the "Data" tab, I can see data coming in.

Any ideas what could be going on?

**Comment by CIPop** [comment]
@damonbarry @varunpuranik @myagley PTAL

**Comment by damonbarry** [comment]
From your description, it sounds like you're using [Device Explorer](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer), which has not been updated yet with features for IoT Edge. The reason you're seeing ConnectionStatus=Disconnected and no Last*Time is because IoT Edge runtime never connects as the _device_; it connects as the Edge Hub and/or Edge Agent _modules_. Since Device Explorer doesn't support modules, it won't show you this information.

For now, you can go to the Azure portal and look in the IoT Edge Explorer tab of your IoT Hub. There, you can click on your edge device and see that it is connected.

**Comment by grtn316** [comment]
Thank you sir.
