### ISSUE TITLE
[Technical Question] [AzureSDK .NET v2] How to use ProvisioningTransportHandlerHttp in ProvisioningDeviceClient

### ISSUE THREAD

**Issue by bastyuchenko** [Azure/azure-iot-sdk-csharp#3246]
Hello,
In my code that based on v1 I use `ProvisioningTransportHandlerHttp`
```
          var provClient = ProvisioningDeviceClient.Create(
                _parameters.GlobalDeviceEndpoint,
                _parameters.IdScope,
                security,
                new ProvisioningTransportHandlerHttp());
```

How to use (or rather what is a replacement for ) `ProvisioningTransportHandlerHttp` (HTTP protocol implementation for the Provisioning Transport Handler) for `ProvisioningDeviceClient` in SDK v2?

**Comment by drwill-ms** [comment]
@bastyuchenko thank you for your continued evaluation of and feedback on our v2 preview SDK. You've been helping making it better and we **really** appreciate it.

We [documented](https://github.com/Azure/azure-iot-sdk-csharp/blob/previews/v2/SDK%20v2%20migration%20guide.md#notable-breaking-changes-6) this in the migration guide for the DPS device client.

HTTP support as a primary protocol of choice has been removed in v2. The DPS client changed to match the IoT Hub client, where it was removed because too many operations were not supported on HTTP, creating a poor experience. A client app that was written specifying MQTT or AMQP to use any and all operations, but later changed to use HTTP would fail at runtime with exceptions when those operations were called.

Your options for initialization are `ProvisioningClientMqttSettings` or `ProvisioningClientAmqpSettings`, which you'll include when initialization the new 4th parameter (documented [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/previews/v2/SDK%20v2%20migration%20guide.md#api-mapping-5)) for client initialization, `ProvisioningClientOptions`.

As always, we welcome your thoughts and feedback.

**Comment by bastyuchenko** [comment]
@drwill-ms thanks for explanation
