### ISSUE TITLE
[Bug Report] v2.0.0 now removed from nuget package

### ISSUE THREAD

**Issue by LukeBallantyne** [Azure/azure-iot-sdk-csharp#3443]
I am not sure if this is a bug but I can't find any any record of why this would have been done

All of the the `v2.0.0` versions of Microsoft.Azure.Devices and Microsoft.Azure.Devices.Client seem to have been removed from the nuget package
https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/2.0.0-preview005
https://www.nuget.org/packages/Microsoft.Azure.Devices/2.0.0-preview005

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/153053441/5b9ce359-2414-4db2-91df-7ea2885f963e)

My understanding was that we should be migrating from `v1.X.X` to `v2.X.X` but now it's gone? 

I see that the repo branch still exists though
https://github.com/Azure/azure-iot-sdk-csharp/tree/previews/v2
with the latest of version `2.0.0-preview008` but just missing from the nuget package

**Comment by timtay-microsoft** [comment]
For context, we don't recommend upgrading to the v2 releases yet even though we shipped a few preview versions. We haven't formally deprecated the v1 releases and replaced them with v2 yet (hence why all the v2 packages had a "-preview" tag). We are still having some internal discussions about whether we will ever do this.

That said, you are still welcome to use the preview v2 releases even if they aren't listed publicly anymore.

**Comment by LukeBallantyne** [comment]
While I understand that these were only preview it was heavily implied that it WILL be happening not IF it happens.

![image](https://github.com/Azure/azure-iot-sdk-csharp/assets/153053441/e14c1663-7d90-458a-9a09-f3d5993cb5e1)

If internal discussions are still taking place, making a decision to remove them from public seems rather odd and somewhat confusing, does this mean you no longer "highly encourage" us to try them out and give feedback?

For context we have been using v2 at my work since it's release into preview in 2022 and have found it to be much better than v1. 

My suggest would be to restore the preview packages into the public nuget package until those internal discussions have been finished, I'm sure we are not the only ones who find the benefits of v2 to outweigh the fact that it's in preview.

Thank you.

**Comment by ryanwinter** [comment]
Hi @LukeBallantyne,

At this point we have no plans to release a v2 SDK which is why we delisted them on NuGet. It was a hard decision given the amount of time and effort that both Microsoft and our customers invested. 

Like Tim mentioned above, we are continuing to have internal discussion relating to future versions of the Azure IoT SDKs family, and this may impact future decisions on the v2 SDK, however at this time there is no development or planned development on this branch.

The recommendation is to continue using the released v1 SDK, there are no plans to deprecate this version. Please continue to file issues you find in GitHub as usual.


Thanks
Ryan

**Comment by timtay-microsoft** [comment]
Closing this thread as per the above
