### ISSUE TITLE
Connection to protocol gateway does not work

### ISSUE THREAD

**Issue by saivendra** [Azure/azure-iot-sdk-csharp#353]
- **OS and version used:** <VERSION> 
Window Server 2016
- **SDK version used:** <VERSION> 
master branch

# Description of the issue:

Connecting to IoT Hub thru Protocol Gateway never succeeds. Device to Protocol Gateway connection is established but Protocol Gateway to IoT Hub does not work. Reason: Potential bug in IotHubConnectionString(IotHubConnectionStringBuilder builder)
# Code sample exhibiting the issue:

Potential Bug in Microsoft.Azure.Device.Client::IotHubConnectionString=>line 31
this.HostName = builder.GatewayHostName == null || builder.GatewayHostName == "" ? builder.HostName : builder.GatewayHostName;

When Protocol Gateway is present in the connection string the HostName is being set to the Protocol Gateway host. Then instead of connecting to Azure IoT Hub the connection is made back to the Protocol Gateway, which is incorrect. Should line 31 in IotHubConnection string instead simply be:
this.HostName = builder.HostName;
With this change the MQTT client is able to connect to IoT Hub thru thr Protocol Gateway
DeviceClient deviceClient = DeviceClient.CreateFromConnectionString(DeviceConnectionString, TransportType.Mqtt);               
deviceClient.OpenAsync().Wait();

# Console log of the issue:

No console log

**Comment by CIPop** [comment]
@saivendra, a new version of the gateway is under development in https://github.com/Azure/azure-iot-sdk-csharp/tree/modules-preview

@damonbarry @myagley is this something that could already be fixed in the modules-preview branch?

**Comment by damonbarry** [comment]
@CIPop Protocol gateway project is [here](https://github.com/Azure/azure-iot-protocol-gateway), and is unrelated to the [modules-preview](https://github.com/Azure/azure-iot-sdk-csharp/tree/modules-preview) branch of this repo, or to IoT Edge. The confusion probably comes from the fact that IoT Edge makes use of the `GatewayHostName` segment of the connection string which was originally designed to be used by the protocol gateway.

@saivendra I'm a little confused by your description. You refer to line 31, but that doesn't match [IotHubConnectionString.cs line 31](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/common/src/service/IotHubConnectionString.cs#L31) in the master branch. Can you double check which branch/commit, file, and line you're referring to?

As far as I know, the SDK _needs to_ set HostName=GatewayHostName in order to connect to the protocol gateway. And then the client that gets used on the backend of the protocol gateway will set HostName=HostName to connect directly to IoT Hub. But oddly, that's not what's happening in the master branch, so it's possible that GatewayHostName has been broken in the master branch for some time. Looking in the `modules-preview` branch, it appears we have made some changes to [IotHubConnectionString.cs](https://github.com/Azure/azure-iot-sdk-csharp/blob/modules-preview/common/src/service/IotHubConnectionString.cs) in order to correctly handle GatewayHostName. We added the GatewayHostName field, and we're making different use of the Audience field.

**Comment by saivendra** [comment]
@damonbarry , you are looking at different code and not the one I am referring to. Please look at [IotHubConnectionString.cs](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/IotHubConnectionString.cs#L31l). The code is setting the HostName to GatewayHostName when there is a Protocol Gateway present. With this code in place the Protocol Gateway is connecting to itself and not Azure IoT Hub.

From my client code, the call deviceClient.OpenAsync().Wait() never returns as the Protocol Gateway is trying to connect to itself. I am simply running the sample MQTT and trying to connect to the Protocol Gateway and the OpenAsyn().Wait() call never returns. My debugging of the SDK code led me to what I have mentioned.

**Comment by damonbarry** [comment]
Ah right...I was looking at the service client code, not device client, sorry.

Perhaps there is a bug in the C# SDK here. But when I look through the git history, the behavior since the beginning has been to use `GatewayHostName` if it is set, otherwise use `HostName`. And I'm pretty sure the C# SDK has worked against protocol gateway in the past (in fact, since the protocol gateway itself uses the C# SDK on the backend, I'm guessing it was used as the front-end client too during development).

Also, you said this works when you use the C SDK. If you look [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L1964) (MQTT) and [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_amqp_common.c#L175) (AMQP), the C SDK does the same thing--it uses `GatewayHostName` if set, otherwise it uses `HostName`.

All this to say I think we'll need to do some deeper investigation...

**Comment by saivendra** [comment]
Great. Please let know what your investigation leads to. My investigation confirms that current C SDK & current Protocol Gateway works as expected. Current C# SDK & current Protocol Gateway is broken. Thanks

**Comment by rcoccia** [comment]
I'm currently working with c# device client 1.6.2 and a protocol gateway that perform decompression of the payload before routing the request to the iot hub. 
my connection string is something like 
HostName=xxx.azure-devices.net;DeviceId=testdevice;GatewayHostName=localhost:8883;SharedAccessKey=xxxx;

I can pass the string to the iothubconnectionstring builder. Accessing properties like HostName or GatewayHostName everything is set like expected

when I open the connection with something like
var deviceClient = DeviceClient.CreateFromConnectionString(cb.ToString(), settings);
i get a invaliduri exception 
Message = "Invalid URI: The hostname could not be parsed."

**Comment by saivendra** [comment]
@rcoccia try without the port number. I believe the port number is hard coded in the SDK
HostName=xxx.azure-devices.net;DeviceId=testdevice;GatewayHostName=localhost;SharedAccessKey=xxxx;

**Comment by CIPop** [comment]
@rcoccia given there are no other comments I'm assuming that @saivendra's answer fixed the problem. Closing for now. Please reopen if you still have issues.
