### ISSUE TITLE
Add default IRetryPolicy documentation

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#355]
Within https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.setretrypolicy?view=azure-dotnet#Microsoft_Azure_Devices_Client_DeviceClient_SetRetryPolicy_Microsoft_Azure_Devices_Client_IRetryPolic we could document the default retry policy.

The default retry policy is defined by the following:
`new ExponentialBackoff(int.MaxValue, TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(10), TimeSpan.FromMilliseconds(100));`

To avoid high CPU usage, the retries are throttled if the code fails immediately (e.g. when there is no network or route to destination) so that the minimum time to execute the next retry is 1 second.

The following graph shows how much delay is _added_ after the initial I/O call failed with a transport error:
![image](https://user-images.githubusercontent.com/8635911/35535315-ffda8316-04f7-11e8-89b5-196bfbbd4fd7.png)

If the service is responding with a throttling error, the retry policy is different and cannot be changed via public API:
`new ExponentialBackoff(RetryCount, TimeSpan.FromSeconds(10), TimeSpan.FromSeconds(60), TimeSpan.FromSeconds(5))`

The retry mechanism will stop after `DefaultOperationTimeoutInMilliseconds` which is currently set at 4 minutes.

**Comment by CIPop** [comment]
@jasmineymlo @yzhong94 @tameraw PTAL

**Comment by yzhong94** [comment]
@BryanLa Adding Bryan as he's helping us with retry documentation

**Comment by BryanLa** [comment]
Thanks @yzhong94. I believe these ref docs are auto-generated (from a corresponding assembly), so I don't know if we have options of updating/augmenting (unless it's put into the source /// comments). So a couple of questions:
- assuming we can't would it make sense to integrate this into the doc Yi is referring to instead?
- is a similar type/API also available to non-.NET clients?

@dominicbetts - I will create a DPS work item to track

**Comment by yzhong94** [comment]
@BryanLa This is not for DPS, you can track it under SDK section.  And yes, we should integrate this into the SDK reliability doc.

**Comment by BryanLa** [comment]
@yzhong94 apologies, I meant to say SDK.. :) So I will just update the existing reliability work item w/this (instead of creating a new one), if that works for everyone.

**Comment by CIPop** [comment]
> assuming we can't would it make sense to integrate this into the doc Yi is referring to instead?

This must be present either directly or via a link on this particular API. Having a blog-post or other document will not help our customers discover the defaults.

> is a similar type/API also available to non-.NET clients?

@BryanLa this functionality should be available or planned for all other languages. This particular API and type is C# specific.

**Comment by CIPop** [comment]
This needs to be documented by using XML doc in the code: https://review.docs.microsoft.com/en-us/help/contribute-ref/?branch=master
We can also add a readme.md to have the image above.

**Comment by BryanLa** [comment]
Agree. I just finished reviewing the options, and this is best path, if we want to keep the link on the reference doc page. 

Specifically, the CI team that owns generation of reference docs has asked that we use the \<remarks\> tag in the /// comments. So we could add something like "See [How to use reliability features in Azure IoT device SDKs](https://review.docs.microsoft.com/azure/iot-dps/how-to-use-sdk-reliability-features?branch=pr-en-us-32087) for more details on retry policy.". I can also incorporate your retry graph in the reliability features article.

When they generate the doc XML from the assembly, it gets stored in the https://github.com/azure/azure-docs-sdk-dotnet repo, which is used for publication to docs.microsoft.com. For example, you can see the XML for the [SetRetryPolicy method here](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/DeviceClient.xml#L996). Also just FYI, this doesn't impact the source code, but they will eventually be converting from an XML to YAML format for publishing auto-gen reference docs.

If this approach doesn't work (ie: putting a "remarks" link in the source code), the only other option is to ask them to take this IoT reference docset out of the CI pipeline. This means they would do a one-time reflection of the assembly to generate Markdown (instead of XML/YAML), and we could do whatever we want in terms of adding content to the SetRetryPolicy docs going forward. The major downside of this approach, is losing the CI, which I don't think is worth doing.
