### ISSUE TITLE
[IoTEdge v2 Modules] Module setup

### ISSUE THREAD

**Issue by rcastill** [Azure/azure-iot-sdk-csharp#383]
I begin apologizing because this is more of a feature request/question than an issue.

I'm using the preview version of the SDK where a module can be created, but there are some things like the module docker's image that are not considered in the module's structure.

Same happens for routes definitions.

These two are steps when creating a module in the portal. So my question is if is there currently a way to define these parameters (even by a REST endpoint)?

I know those are defined in the desired properties of `$edgeAgent` and `$edgeHub` respectively but I'm not allowed to modify those since they're system modules.

To conclude I'd like to add that when I call `Registry.CreateModule` it works (returns the created module info) but this is not reflected on the portal. May it be because of the missing configurations? (`$edgeAgent` and `$edgeHub` do not appear in the portal unless a module has being fully set)

**Comment by CIPop** [comment]
Thanks for reporting @rcastill : definitely no need to apologize!

@damonbarry @myagley PTAL

**Comment by damonbarry** [comment]
@rcastill 

> there are some things like the module docker's image that are not considered in the module's structure

A module's docker image is set in the `$edgeAgent` module's twin (desired properties), not a module's own twin.

If you want to update various aspects of the `$edgeAgent` and `$edgeHub` module twins via the SDK, you can use either:
- `RegistryManager.ApplyConfigurationContentOnDeviceAsync` to set the configuration on a single device (this is what the portal uses when you press the "Set Modules" button)
- `RegistryManager.AddConfigurationAsync` to create a deployment that can apply to any number of devices (depending on the Target Condition--this is what the portal uses when you press the "Add IoT Edge Deployment" button). There are also `GetConfigurationAsync`, `RemoveConfigurationAsync`, `UpdateConfigurationAsync` methods. They're poorly documented right now, but that should improve over time.

> when I call Registry.CreateModule it works (returns the created module info) but this is not reflected on the portal.

Correct. The portal currently shows "Deployed Modules", not all modules. I believe there's work happening to improve the portal so that you can do modules-related stuff in a more generalized way.

**Comment by rcastill** [comment]
@damonbarry that was what I was looking for, thanks!
