### ISSUE TITLE
ScheduleDeviceMethodAsync not working properly

### ISSUE THREAD

**Issue by carlosaxpires** [Azure/azure-iot-sdk-csharp#40]
I'm able to schedule (queue) a new job using JobClient.ScheduleDeviceMethodAsync method, however, the result is always "Failed" with the following error: 

SQL query parse failed due to following errors: 
	Line 1:29 Unexpected character at input 'SELECT': @Microsoft.Azure.Devices.DeviceManagement.JobService.Orchestrations.IMultipleDevicesOrchestrationManager.QueryDevicesAsync

The query that I'm sending is the same as in the documentation: "SELECT * FROM devices"

Am I doing something wrong? Or is the IoT service not working on Azure?

(SDK Version: 1.2.1)

Thanks!

**Comment by compsri** [comment]
Hey Carlos,

Documentation regarding scheduling Jobs is here: [Schedule jobs on multiple devices](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-jobs)

Per the documentation, queryCondition is the WHERE part of a SQL query. For e.g., `"deviceId IN ['MyDevice1','MyDevice2']"`.

Based on the error you posted, it looks like you're trying to schedule a job on all the devices in the hub. Unfortunately, because providing a queryCondition is a MUST as of now, this is unsupported currently. We are going to fix this issue soon. In the interim, you can get the desired result by using the following queryCondition: `"IS_DEFINED(DeviceId)"`

Thanks!

**Comment by tameraw** [comment]
@carlosaxpires - We will close this issue as we believe you have a work around for now. Feel free to reopen if this doesn't meet your needs. Thanks.
