### ISSUE TITLE
DeviceClient.OpenAsync() is not working as expected

### ISSUE THREAD

**Issue by Meandron** [Azure/azure-iot-sdk-csharp#419]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 7
- **Application's .NET Target Framework :** <NETVERSION> 
.Net Framework 4.5.2
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 
SDK version 1.7.0

# Description of the issue:

- DeviceClient.OpenAsync() seems not to validate the connection string that has been passed in the course of instance creation.  I would expect OpenAsync() to do it: Or how can i be sure a connection string is valid **before** sending messages to a IoT Hub?
- ConnectionStatusChangesHandler is never hit

# Code sample exhibiting the issue:

```C#
    class Program
    {
        static void Main(string[] args)
        {
           AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException; //just do make sure I'm not missing something
           OpenClient();
           Console.ReadKey();        
        }

        private static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            Console.WriteLine(e); //never hit
        }

        public static void OpenClient()
        {
            String azureString = "HostName=invalidHost.net;DeviceId=invalidClient;SharedAccessKey=<someKey>";
            DeviceClient client = DeviceClient.CreateFromConnectionString(azureString, TransportType.Http1);
            client.OperationTimeoutInMilliseconds = 2000;
            try
            {

                client.SetConnectionStatusChangesHandler(Mystatushandler);
                client.OpenAsync().Wait();
                client.SendEventAsync(new Message()).Wait();
            }
            catch (Exception e)
            {
                //client.SendEventAsync() throws timeout in case of invalid connecting string
            }
        }

        private static void Mystatushandler(ConnectionStatus status, ConnectionStatusChangeReason reason)
        {
            //never hit, even with valid connection string
        }
    }
```
# Console log of the issue:

**Comment by CIPop** [comment]
> DeviceClient.OpenAsync() seems not to validate the connection string that has been passed in the course of instance creation

/cc @yzhong94 @tameraw @abhipsaMisra @zolvarga 

__TLDR__: This is by design. Workaround: use a connection oriented protocol such as MQTT(/WS) AMQP(/WS).

__In detail__:
We allow the `OpenAsync` API as a no-op for HTTP to allow applications to easily switch between HTTP, AMQP, MQTT (over WS) protocols. Since HTTP will not maintain an open connection (except for Keep-Alive and HTTP connection pooling which are HTTP-stack dependent and outside of our control) only an actual operation (`SendEventAsync`) will attempt to perform network I/O (and, in this case validate the DNS).

While I see your point in having OpenAsync perform a test even for HTTP, I see downsides:
1. Even if we would perform a read-only operation to validate the remote endpoint, since HTTP can (and versions 1.0/1.1 will) use different TCP connections, they could go through different routes. This means that if the first request succeeds it does not guarantee that subsequent requests will take the same path (and so, could fail). 
2. This operation would cause network traffic which is not desired in low-bandwidth, costed networks or battery operated devices.

If you still think having such a test performed in HTTP OpenAsync, please reopen this issue and add more details about the scenario that you're trying to solve.

**Comment by yzhong94** [comment]
@Meandron , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by Meandron** [comment]
@CIPop 
I see you point - due to security restricitions I cannot switch to AMPQ or MQTT but need to make sure that a IoT hub connection is validated on application startup to be able to "fail fast": It's unknown when data will arrive at the application to be transferred to Azure - it may take days or even weeks until data is available. Is there a way I can validate the connection string using HTTP(S) without actually sending data?
