### ISSUE TITLE
RegistryManager Query results returns 'offline' for online devices

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-iot-sdk-csharp#448]
Not sure if this is a bug or a limitation, but it's definitely not ideal that the real connection state is **always** set to `Disconnected` even if via the portal the state is `Connected`. This is especially important if your team is planning to go through on its threat to remove operations monitoring. 

Online/offline states should trigger twin change events as well

```json
{
  "deviceId": "***",
  "etag": "AAAAAAAAAAE=",
  "status": "enabled",
  "statusUpdateTime": "0001-01-01T00:00:00-06:00",
  "connectionState": "Disconnected",
  "lastActivityTime": "0001-01-01T00:00:00-06:00",
  "cloudToDeviceMessageCount": 0,
  "authenticationType": "sas",
  "x509Thumbprint": {
    "primaryThumbprint": null,
    "secondaryThumbprint": null
  }
}
```

**Comment by zolvarga** [comment]
@onionhammer 

Thanks for reporting the issue we will take a look at it.

Best Regards,
Zoltan

**Comment by CIPop** [comment]
@onionhammer this seems similar to #510. Can you get the updated value if you query using `GetTwinAsync`? 

If it's the same bug, please close this one and open a Support Request from within your Azure Subscription so that the service team can debug.

Tentatively closing this issue, please reopen if this is not the same issue.
