### ISSUE TITLE
Failure in authenticating device(Csdk)with X509 certificate.

### ISSUE THREAD

**Issue by Manikandan84** [Azure/azure-iot-sdk-csharp#497]
I have created a device code with the latest iot client C sdk.I have created a 30 day trail Ca certificate using power shell scripts.The certificate has been added to azure portal and verified for possession.
I created device leaf certificate and updated my public and private keys in my device code.

Do i need to update ny other details in cert.c file.

On connecting to azure ,I get 0x05 Unauthorized error.

- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by anthonyvercolano** [comment]
Couple of things here.

You shouldn't need to adjust your cert.c.  This contains the SERVER chain of certificates.  This ensures that you can validate that the SERVER is who it says it is.

Typically for c applications when I have seen un authorized it is because of incorrect use of the terminating line feed / cr in the included cert or private key.

More importantly you want to raise this un-auth problem as an issue in the
github.com/azure/azure-iot-sdk-c repo.

**Comment by zolvarga** [comment]
Closing as it answered and also it is in wrong repo.
Please open an issue in C repo if you would need further help.

Best regards,
Zoltan
