### ISSUE TITLE
CloudToDeviceMethod is not implemented in UWP

### ISSUE THREAD

**Issue by castics** [Azure/azure-iot-sdk-csharp#50]
Azure IoT Hub direct methods [CloudToDeviceMethod](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.cloudtodevicemethod) are not implemented in Microsoft.Azure.Devices for UWP. There is an exception "missing API 2!" in [InvokeDeviceMethodAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient#Microsoft_Azure_Devices_ServiceClient_InvokeDeviceMethodAsync_System_String_Microsoft_Azure_Devices_CloudToDeviceMethod_).

Found the following code in [HttpClientHelper.cs](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/service/Microsoft.Azure.Devices/HttpClientHelper.cs)
`#if WINDOWS_UWP`
`throw new NotImplementedException("missing API 2!");`
`#else`
`requestMsg.Content = new ObjectContent<T1>(entity, JsonFormatter);`
`#endif`

**Comment by tameraw** [comment]
@castics - Thanks for filing this. Unfortunately, this is currently not supported for UWP.

**Comment by nickverschueren** [comment]
@tameraw - Because this is not supported for UWP, it is now also not supported for NetStandard 1.3 it seems. This is a very strange limitation. This limitation also means you cannot do queries on the RegistryManager, which I find very annoying.
On my own fork I have replaced the offending line (the throw) with:
`
var str = Newtonsoft.Json.JsonConvert.SerializeObject(entity);
requestMsg.Content = new StringContent(str, System.Text.Encoding.UTF8, "application/json");
`
This is used several times in the same file already (Put and Patch) and works perfectly, so why is it not used for Post?

**Comment by zyofeng** [comment]
Do we have any progress on this? I am using asp.net core to call CloudToDeviceMethod on iot devices connected to Azure iot hub, the only way to get around the method not implemented issue is to change target framework from netcoreapp1.1 to net462. Not ideal.

**Comment by jasmineymlo** [comment]
This is fixed dc1c5651d7010d72b4fe14a121e9185674008c52 and released.  Thanks.
