### ISSUE TITLE
Trying to install the Microsoft.azure.devices 1.2.2 to a windows service 

### ISSUE THREAD

**Issue by hatimnagarwala** [Azure/azure-iot-sdk-csharp#51]
I am getting an error 

Could not install package 'Microsoft.Azure.Devices 1.2.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Trying this in a windows service, but unable to do the same.

**Comment by tameraw** [comment]
@hatimnagarwala - Currently the Microsoft.Azure.Devices library supports .NETFramework version 4.5.1 or greater. Any issues moving to 4.5.1 on your side?

**Comment by hatimnagarwala** [comment]
Yes I was working on a windows service which was targeted to .net framework 4.5 but it still didn't work.

**Comment by sergaz-msft** [comment]
Hello @hatimnagarwala can you go ahead and try using .net framework 4.5 with the latest version of the sdk? Thanks

**Comment by sergaz-msft** [comment]
@hatimnagarwala 
If you compile the service and device sdk for .NET45 you will have the dlls on that version. Change the properties (Target Framework to .NET Framework 4.5) on the following projects:

**Service**

- Microsoft.Azure.Devices
- Microsoft.Devices.Shared

**Client**

- Microsoft.Azure.Devices.Client

On your project, instead of adding the NuGet package can you reference the Dlls for the compiled ones?
Let me know the results.
Thanks!

**Comment by sergaz-msft** [comment]
Hello @hatimnagarwala ,
Letting you know that the next release of the SDK will include support for .NET45 in the Nuget package.
All Best

**Comment by hatimnagarwala** [comment]
@sergaz-msft thanks a lot for the support 👍
