### ISSUE TITLE
Connect to device using DeviceAuthenticationWithToken

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-csharp#536]
- **OS, version, SKU and CPU architecture used:** Windows 10
- **Application's .NET Target Framework :** .Net 4.7.1
- **Device:** Windows console simulator
- **SDK version used:** Latest from nuget
## Description of the issue:
I want to connect to device from device client using Shared Access Signature (SAS token). I created a sas token using the following code and used the SAS token in DeviceClient,Create method. When sending messages to the device I get UnauthorizedException - CONNECT failed: refusednotauthorized

Please help
## Code sample exhibiting the issue:

Code snippet for generating SAS token:

public string GenerateSasToken(string resourceUri, string key, string deviceId, string policyName = null, int expiryInSeconds = 3600)
        {
            TimeSpan fromEpochStart = DateTime.UtcNow - new DateTime(1970, 1, 1);
            string expiry = Convert.ToString((int)fromEpochStart.TotalSeconds + expiryInSeconds);

            string stringToSign = WebUtility.UrlEncode(resourceUri) + "\n" + expiry;

            HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(key));
            string signature = Convert.ToBase64String(hmac.ComputeHash(Encoding.UTF8.GetBytes(stringToSign)));

            string token = String.Format(CultureInfo.InvariantCulture, $"SharedAccessSignature sr={WebUtility.UrlEncode(resourceUri)}/devices/{deviceId}&sig={WebUtility.UrlEncode(signature)}&se={expiry}");

            if (!String.IsNullOrEmpty(policyName))
            {
                token += "&skn=" + policyName;
            }

            return token;
        }

Code snippet where the device client is created:

s_deviceClient = DeviceClient.Create(s_iotHubUri, new DeviceAuthenticationWithToken("MyDevice009", "SharedAccessSignature sr=xxx-xxxxxx-xxxxx-iot-01.azure-devices.net/devices/MyDevice009&sig=%2B6TmLd6q4ZQDfg6fa0TMJaEVeuA%2BmKQPBGZTmcqNpBc%3D&se=1530184625"),TransportType.Mqtt);

**Comment by CIPop** [comment]
@amogh79 Instead of duplicating that code, my recommendation is to instead derive from `SharedAccessSignatureBuilder` and override the `Sign` function only. The other advantage is that it would work even if future SDKs/Service versions decide to change the token format. (Still, custom implementations would still be impacted if, for security reasons, we will ever need to change the HMACSHA256 to something stronger.)

See [TpmSharedAccessSignatureBuilder ](https://github.com/Azure/azure-iot-sdk-csharp/blob/cd93e75fd8914b6247f23eb6a5cfd7aea459676f/iothub/device/src/DeviceAuthenticationWithTpm.cs#L50) for reference.

You can also take advantage of the `DeviceAuthenticationWithTokenRefresh` in case you need to implement your own token generation algorithms.

If you still want to go with a vanilla generator, I would start by diffing your code with the one in `SharedAccessSignatureBuilder` to check for errors.

**Comment by amogh79** [comment]
@CIPop Thanks for your response. Finally I went ahead and used SharedAccessSignatureBuilder.ToSugnature() method but what makes me wonder why is the code that I copied from MS documentation site is not working. I copied the code from here - [https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token]

**Comment by CIPop** [comment]
>  I copied from MS documentation site is not working. I copied the code from here - [https://docs.microsoft.com/en-us/rest/api/__eventhub__/generate-sas-token]

@amogh79 Glad it worked! I believe the doc is only for EventHub. SAS token formats can be different between Azure services.
