### ISSUE TITLE
Microsoft.Azure.Devices.Client 1.17.0 does not work with Microsoft.Azure.Amqp 2.3.0

### ISSUE THREAD

**Issue by IshamMohamed** [Azure/azure-iot-sdk-csharp#559]
According to Nuget specifications - https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.17.0, Microsoft.Azure.Devices.Client 1.17.0 will work without any problem in .NET Framework if we have Microsoft.Azure.Amqp (>= 2.2.0). In my case, developing an Azure Function, in the same project I had to use Microsoft.Azure.ServiceBus 3.0.2, in which the dependency is Microsoft.Azure.Amqp (>= 2.3.0 && < 3.0.0). Thus in my Azure functions project I have Microsoft.Azure.Amqp 2.3.0. 

I am getting an error : `Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`

**Comment by CIPop** [comment]
Thanks for reporting @IshamMohamed !

There are two solutions:
1. If you need to use the older version, please use [Binding Redirect](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element) to allow the compiler to use different versions. Also see the issue here: https://github.com/Azure/azure-amqp/issues/110#issuecomment-409357250 . This is not guaranteed to work if backward-API compat was not preserved in the dependencies. In projects using [SemVer ](https://semver.org/) you can usually redirect to the same major-version of the dependency.

2. We've released [1.17.1 ](https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.17.1) in which I've updated the dependency to AMQP 2.3.2.

**Comment by IshamMohamed** [comment]
AFAIK, Binding Redirect is yet to be supported in Azure Functions, isnt it?

**Comment by CIPop** [comment]
@IshamMohamed - Binding Redirect is a csproj concept. I admit I'm not very familiar with Azure Functions but @jenoola was successful in using our SDK. She pointed out that VS2017 (latest update) has automatic binding redirects enabled.

Please let us know if manual or automatic Binding Redirect doesn't unblock you.
