### ISSUE TITLE
AddDeviceAsync (new Device(deviceID) throws null exception when used in Azure Function

### ISSUE THREAD

**Issue by anhashia** [Azure/azure-iot-sdk-csharp#562]
- **OS, version, SKU and CPU architecture used:** <VERSION> Azure Function
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> "Microsoft.Azure.Devices": "1.16.0"

## Description of the issue:
manager.AddDeviceAsync throws **argument null** exception when used inside Azure Function.
This issue **doesn't** happen in simple console application used on Windows 10

## Code sample exhibiting the issue:
```
const string deviceID = "mydevice101";
RegistryManager manager = RegistryManager.CreateFromConnectionString(connectionString);
await manager.AddDeviceAsync(new Device(deviceID));
```
## Log from Azure Function console

2018-07-24T00:41:27.872 [Error] Exception while executing function: Functions.EventHubTriggerCSharp1. Microsoft.Azure.WebJobs.Script: One or more errors occurred. Microsoft.Azure.Devices: 

``{"Message":"ErrorCode:ArgumentNull;BadRequest","ExceptionMessage":"Tracking ID:a9dceefc5a454482a8c99379f870abcb-G:0-TimeStamp:07/24/2018 00:41:27"} ``

**Comment by anhashia** [comment]
Similar to #54 in some sense

**Comment by anhashia** [comment]
Works fine with **older** version of SDK
```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.Azure.Devices": "1.4.1"
      }
    }
   }
}

```
Add device scenario seems to have regressed in version **1.5.0** and above when used in **Azure Function**

**Comment by seank-com** [comment]
Thanks for opening this @anhashia

**Comment by CIPop** [comment]
Thanks @anhashia for reporting - we'll need to investigate why this is different in an Azure function vs console app.

**Comment by CIPop** [comment]
@jenoola is investigating the corresponding ICM for this GitHub issue.
@jenoola please add your findings here as well.

**Comment by jenoola** [comment]
@anhashia here is a workaround we found. Our SDK works fine with Azure functions v2 that are available for .NETStandard projects. Azure Functions v1 on .NETFramework run into binding issues and that causes some errors, we are still investigating why. Meanwhile, please try to make these changes to your project to switch to Azure Functions v2:

csproj file:
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
    <UseNETCoreGenerator>true</UseNETCoreGenerator>
</PropertyGroup>

host.json:
{
  "version": "2.0"
}

local.settings.json:
{
  ...
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    ...
  }
}

NuGet dependencies:
Microsoft.Azure.Devices latest version
Microsoft.NET.Sdk.Functions latest version
Newtonsoft.Json latest version
NETStandard.Library 2.0.3

And use ILogger from Microsoft.Extensions.Logging instead of TraceWriter

Please let us know if this helps.

**Comment by jenoola** [comment]
Additional information from Azure Functions team: it's a known issue that Azure Functions v1 do not work with certain versions of Newtonsoft. They do recommend to switch to Azure Functions v2 on .NETStandard, as v1 won't be fixed

**Comment by az-iot-builder-01** [comment]
@seank-com, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
