### ISSUE TITLE
SetupDeviceExplorer.msi no longer available

### ISSUE THREAD

**Issue by joncoons** [Azure/azure-iot-sdk-csharp#668]
- **OS, version, SKU and CPU architecture used:** <VERSION> All - **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION> 

## Description of the issue:
The link to the pre-built Device Explorer works, but the SetupDeviceExplorer.msi is no longer available on the https://github.com/Azure/azure-iot-sdk-csharp/releases page.

**Comment by CIPop** [comment]
@joncoons we have not released DeviceExplorer since https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2018-3-13 .
We are keeping this product in maintenance mode: no new features will be added. Instead we're recommending using the Portal which supports new features such as Edge and Modules.

**Comment by az-iot-builder-01** [comment]
@joncoons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
