### ISSUE TITLE
Unable to explicitly open device client once it is explicitly closed

### ISSUE THREAD

**Issue by Perun85** [Azure/azure-iot-sdk-csharp#673]
**Description**
Unable to explicitly open device client once it is explicitly closed. I am getting **ObjectDisposedException**. Is this by design?

**Framework versions:**  .NET 4.7.1
**Library:** Microsoft.Azure.Devices.Client 1.18.1
**OS Version:** Windows 10 Pro (Version: 1803, OSBuild: 17134.345)

**StackTrace**:
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DotNet.Program.<Main>d__0.MoveNext() 

**Steps to reporoduce**:
Replace Main method of Console application (Core or DotNet) with following snippet and change C# version to 7.3. Replace [yourvalue] tags with appropriate values.

```
using Microsoft.Azure.Devices.Client;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;

namespace DotNet
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var cert = new X509Certificate2("[yourvalue].pfx","[yourvalue]");
            var authMethod = new DeviceAuthenticationWithX509Certificate("[yourvalue]", cert);
            var deviceClient = DeviceClient.Create("[yourvalue]", 
                authMethod, TransportType.Amqp_Tcp_Only);

            var message = new Message(Encoding.UTF8.GetBytes("Test client"));

            await deviceClient.CloseAsync();
            await deviceClient.OpenAsync();

            await deviceClient.SendEventAsync(message);
        }
    }
}
```
If you need more information, please let me know.

**Comment by CIPop** [comment]
> Unable to explicitly open device client once it is explicitly closed. 

@Perun85 yes, not being able to reuse the object is expected. AFAIK, this is in-line with other .NET networking APIs.

> I am getting ObjectDisposedException. Is this by design?

No: this part is a bug. Since _you_ didn't dispose of the object, this is the wrong exception. 
This needs to be fixed by throwing an `InvalidOperationException("DeviceClient/ModuleClient cannot be resued after calling CloseAsync()")`.

**Comment by Perun85** [comment]
Thank you for clarification.  

My intention was to close connection and to place object in cache and when needed to initialize connection again without crating new instance of DeviceClient.  Getting ObjectDisposedException lead me to believe that it is actually possible and that there is small issue in library itself.

**Comment by CIPop** [comment]
@Perun85 We are changing the decision to change the second portion. Due to strict app-compat rules (https://github.com/Azure/azure-iot-sdk-csharp/blob/master/doc/devguide.md#design) we will continue throwing ObjectDisposedException as we did in previous versions (1.18).
This is a related enhancement: https://github.com/Azure/azure-iot-sdk-csharp/issues/984. We will still not allow Open, Close, Open.

**Comment by az-iot-builder-01** [comment]
@CIPop, @Perun85, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
