### ISSUE TITLE
Is web socket supported in .NET Core while using DeviceClient ? throwing "System.Net.WebSockets.WebSocketException exception

### ISSUE THREAD

**Issue by kudlatiger** [Azure/azure-iot-sdk-csharp#727]
I have written console application using .NET Core 2.1.

The responsibility of this application is: Connect to the Azure IoT hub and send data.

I am still getting below exception

> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at System.Net.Security.SslState.StartSendAuthResetSignal

**Note**:

1. I am running my code on Windows 7 compact OS device.
2. Using web sockets
3. Works fine in Windows 10

**Here is my nuget references**

 

>   using Microsoft.Azure.Devices.Client;
>   using Microsoft.Azure.Devices.Shared;

This is how I create connection.

>    string deviceConnectionString = "*******";
  _Client = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Mqtt_WebSocket_Only);

web sockets will not work on windows 7. Reference: Using WebSocket on Windows 7

So I am using .NET Core 2.1 to get web socket support, as mentioned here https://github.com/dotnet/corefx/issues/20191

Still I get the same error!

what does below means?

The remote certificate is invalid according to the validation?

**Comment by CIPop** [comment]
@kudlatiger the error indicates that you are trying to connect to a TLS endpoint that has failed certificate authentication.

WebSocket uses HTTPS for authentication: the server responds with a certificate that either doesn't match the name of the server, expired or is otherwise invalid.
To debug this, try connecting to the host (Azure IoT Hub) using https://<name> with a browser. If you see certificate invalid you can inspect the fields and check to see why the connection fails.

See more at https://blogs.msdn.microsoft.com/jpsanders/2009/09/16/troubleshooting-asp-net-the-remote-certificate-is-invalid-according-to-the-validation-procedure/

**Comment by az-iot-builder-01** [comment]
@kudlatiger, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by kudlatiger** [comment]
I tried to browse as you have mentioned 

> https://somesite.azure-devices.net/

But it throws below error

> "Message": "ErrorCode:InvalidProtocolVersion;BadRequest",
