### ISSUE TITLE
Are you planning to add support for iot hubs in dotnetcore or universal?

### ISSUE THREAD

**Issue by spacedsweden** [Azure/azure-iot-sdk-csharp#9]

**Comment by tameraw** [comment]
Already have support for UWP. Please take a look and let us know of any feedback.
https://github.com/Azure/azure-iot-sdk-csharp/tree/master/device/Microsoft.Azure.Devices.Client.UWP
https://github.com/Azure/azure-iot-sdk-csharp/tree/master/service/Microsoft.Azure.Devices.Uwp

**Comment by keesschollaart81** [comment]
The UWP support is great but support for .net core would be much better because this enables so many scenario's. For now, if I want to connect my Raspberry Pi to IoT Hub (using c#), my only option is Windows IoT core with an UWP app. If I could run the deviceclient on .net core I could connect from so many (much smaller/cheaper) Linux/ARM based devices...

**Comment by keesschollaart81** [comment]
Similar question is still open over here... https://github.com/Azure/azure-iot-sdks/issues/887
